// Shared test helper for the `registry_data_capture.json` byte-identity fixture
// (issue #109 pre-baked full registry NBT). Never a standalone module — it is
// `include!`d into both consumers, so the prose here uses plain comments rather
// than a `//!` module doc (which `include!` would attach to the includer):
// - `offline_login.rs` (integration test) at crate top level;
// - `registry_sync.rs`'s `#[cfg(test)] mod tests` mid-module.
// The hex decoder lives in exactly one place. Test-only; never production.

/// Parse the committed `registry_data_capture.json` fixture: registry key -> the
/// canonical capture's packet body (a client that accepted no known packs, so
/// every element carries full content). Generated by
/// `tools/rivet-codegen/decode_capture_nbt.py` from the pinned join capture.
fn registry_data_capture_bodies() -> std::collections::HashMap<String, Vec<u8>> {
    let json = include_str!("../fixtures/registry_data_capture.json");
    let value: serde_json::Value = serde_json::from_str(json).expect("parse fixture");
    let object = value.as_object().expect("fixture is an object");
    object
        .iter()
        .map(|(key, body)| {
            let hex = body.as_str().expect("fixture body is a hex string");
            let bytes = (0..hex.len())
                .step_by(2)
                .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("valid hex"))
                .collect();
            (key.clone(), bytes)
        })
        .collect()
}
