//! `rivet-codegen generate` — read the extracted block-state JSON and emit Rust
//! registry source directly into `crates/rivet-registry/src/generated/`, and
//! consume the pinned `data/reports/packets.json` to emit the `rivet-protocol`
//! packet-ID tables (see [`crate::packets`]).

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::model::{BlockDef, BlockRegistry};

pub fn default_input(repo_root: &Path) -> PathBuf {
    repo_root.join("tools/rivet-codegen/data/block_states.json")
}

/// Generated tables are written directly into the `rivet-registry` crate so the
/// committed output cannot drift from what the generator produces.
pub fn default_output(repo_root: &Path) -> PathBuf {
    repo_root.join("crates/rivet-registry/src/generated")
}

pub fn run(
    input_flag: Option<&Path>,
    output_flag: Option<&Path>,
    packets_flag: Option<&Path>,
    packets_output_flag: Option<&Path>,
) -> Result<()> {
    run_blocks(input_flag, output_flag)?;
    crate::packets::run(packets_flag, packets_output_flag)
}

fn run_blocks(input_flag: Option<&Path>, output_flag: Option<&Path>) -> Result<()> {
    let repo_root = crate::extract::find_repo_root()?;
    let input = match input_flag {
        Some(p) => p.to_path_buf(),
        None => default_input(&repo_root),
    };
    let output = match output_flag {
        Some(p) => p.to_path_buf(),
        None => default_output(&repo_root),
    };

    let data: BlockRegistry = serde_json::from_str(
        &fs::read_to_string(&input).with_context(|| format!("read {}", input.display()))?,
    )
    .with_context(|| format!("parse {}", input.display()))?;

    // Deduplicate (name, values) property types globally, preserving order of
    // first appearance. Ordering of values is preserved from the jar.
    let mut prop_index = HashMap::new();
    let mut prop_names: Vec<String> = Vec::new();
    let mut prop_values: Vec<Vec<String>> = Vec::new();
    let mut prop_variants: Vec<String> = Vec::new();

    let mut block_shapes: Vec<(u16, Vec<u16>)> = Vec::new();

    for block in &data.blocks {
        let mut shape: Vec<u16> = Vec::with_capacity(block.properties.len());
        for prop in &block.properties {
            let key = (prop.name.clone(), prop.values.clone());
            let idx = match prop_index.get(&key) {
                Some(&i) => i,
                None => {
                    let i = prop_names.len() as u16;
                    prop_index.insert(key.clone(), i);
                    prop_names.push(prop.name.clone());
                    prop_values.push(prop.values.clone());
                    prop_variants.push(variant_name(&prop.name, &prop_variants[..i as usize]));
                    i
                }
            };
            shape.push(idx);
        }
        if !shape.is_empty() {
            block_shapes.push((block.id, shape));
        }
    }

    fs::create_dir_all(&output).with_context(|| format!("create {}", output.display()))?;

    let header = format!(
        "// Generated by `tools/rivet-codegen generate` from data/block_states.json (MC {}).\n// Do not edit by hand — PORTING.md: registries/data are generated, not hand-ported.\n\n",
        data.minecraft_version
    );

    fs::write(output.join("mod.rs"), format!("{header}{}", render_mod()))
        .context("write generated/mod.rs")?;
    fs::write(
        output.join("blocks.rs"),
        format!("{header}{}", render_blocks(&data)?),
    )
    .context("write generated/blocks.rs")?;
    fs::write(
        output.join("block_properties.rs"),
        format!(
            "{header}{}",
            render_block_properties(&prop_names, &prop_values, &prop_variants, &block_shapes)
        ),
    )
    .context("write generated/block_properties.rs")?;

    let distinct_props = prop_names.len();
    println!(
        "Wrote {} blocks, {} distinct state-property types, {} per-block state shapes -> {}",
        data.blocks.len(),
        distinct_props,
        block_shapes.len(),
        output.display()
    );
    Ok(())
}

/// The generated module file: declares the two generated submodules.
fn render_mod() -> String {
    "pub mod block_properties;\npub mod blocks;\n".to_string()
}

/// `axis` -> `Axis`, `creaking_heart_state` -> `CreakingHeartState`. Appends a
/// numeric suffix (`Facing2`, `Facing3`) when the CamelCase name collides with
/// an earlier variant (a distinct `(name, values)` set sharing the same name).
fn variant_name(name: &str, existing: &[String]) -> String {
    let base = name
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect::<String>();
    if base.is_empty() {
        return "Property".to_string();
    }
    let mut candidate = base.clone();
    let mut n = 2;
    while existing.iter().any(|e| e == &candidate) {
        candidate = format!("{base}{n}");
        n += 1;
    }
    candidate
}

fn render_blocks(data: &BlockRegistry) -> Result<String> {
    // Sanity: registry ids must be contiguous 0..n for the id-indexed array.
    let mut ids: Vec<u16> = data.blocks.iter().map(|b| b.id).collect();
    ids.sort_unstable();
    for (i, id) in ids.iter().enumerate() {
        if *id as usize != i {
            bail!(
                "block registry ids are not contiguous (expected {} at index {i}); adjust the generator",
                id
            );
        }
    }

    // Emit in registry-id order so `BLOCK_BY_ID`'s id == index invariant holds
    // by construction, independent of the source JSON's block ordering.
    let mut blocks: Vec<&BlockDef> = data.blocks.iter().collect();
    blocks.sort_unstable_by_key(|b| b.id);

    let mut out = String::new();
    out.push_str("/// A numeric vanilla block id (index into the `minecraft:block` registry).\n");
    out.push_str("#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]\n");
    out.push_str("pub struct BlockId(pub u16);\n\n");

    out.push_str("/// Block name -> registry id.\n");
    out.push_str("pub static BLOCK_BY_NAME: phf::Map<&'static str, u16> = phf::phf_map! {\n");
    for b in &blocks {
        out.push_str(&format!("    {:?} => {}u16,\n", b.name, b.id));
    }
    out.push_str("};\n\n");

    out.push_str("/// Block names indexed by registry id (id == index).\n");
    out.push_str("pub static BLOCK_BY_ID: &[&str] = &[\n");
    for b in &blocks {
        out.push_str(&format!("    {:?}, // {}\n", b.name, b.id));
    }
    out.push_str("];\n\n");

    out.push_str("impl BlockId {\n");
    out.push_str(
        "    #[inline]\n    pub const fn from_id(id: u16) -> Self {\n        Self(id)\n    }\n\n",
    );
    out.push_str("    pub fn from_name(name: &str) -> Option<Self> {\n");
    out.push_str("        BLOCK_BY_NAME.get(name).copied().map(Self)\n    }\n\n");
    out.push_str("    pub fn name(self) -> &'static str {\n");
    out.push_str(
        "        BLOCK_BY_ID.get(self.0 as usize).copied().unwrap_or(\"minecraft:air\")\n    }\n\n",
    );
    out.push_str("    #[inline]\n    pub const fn id(self) -> u16 {\n        self.0\n    }\n}\n");

    Ok(out)
}

fn render_block_properties(
    prop_names: &[String],
    prop_values: &[Vec<String>],
    prop_variants: &[String],
    block_shapes: &[(u16, Vec<u16>)],
) -> String {
    let mut out = String::new();

    out.push_str("/// One distinct state-property type (a property name plus its\n");
    out.push_str("/// ordered value set, e.g. `axis: [x, y, z]`). Discriminant order\n");
    out.push_str("/// matches first appearance across the block registry.\n");
    out.push_str("#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]\n");
    out.push_str("#[repr(u16)]\n");
    out.push_str("pub enum BlockPropertyId {\n");
    for (i, v) in prop_variants.iter().enumerate() {
        let doc = format!(
            "    /// `{}`: [{}]",
            prop_names[i],
            prop_values[i].join(", ")
        );
        out.push_str(&format!("{doc}\n    {v} = {i},\n"));
    }
    out.push_str("}\n\n");

    out.push_str("/// Property name by `BlockPropertyId` discriminant.\n");
    out.push_str("pub static BLOCK_PROPERTY_NAMES: &[&str] = &[\n");
    for n in prop_names {
        out.push_str(&format!("    {n:?},\n"));
    }
    out.push_str("];\n\n");

    out.push_str("/// Ordered value sets by `BlockPropertyId` discriminant.\n");
    out.push_str("pub static BLOCK_PROPERTY_VALUES: &[&[&str]] = &[\n");
    for vals in prop_values {
        out.push_str("    &[");
        for (j, v) in vals.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{v:?}"));
        }
        out.push_str("],\n");
    }
    out.push_str("];\n\n");

    out.push_str("impl BlockPropertyId {\n");
    out.push_str("    pub fn name(self) -> &'static str {\n");
    out.push_str("        BLOCK_PROPERTY_NAMES[self as usize]\n    }\n\n");
    out.push_str("    pub fn values(self) -> &'static [&'static str] {\n");
    out.push_str("        BLOCK_PROPERTY_VALUES[self as usize]\n    }\n}\n\n");

    out.push_str(
        "/// Per-block state shape: `(block_id, &[property ids in declaration order])`.\n",
    );
    out.push_str("/// Blocks with no properties are omitted.\n");
    out.push_str("pub static BLOCK_STATE_SHAPES: &[(u16, &[u16])] = &[\n");
    for (block_id, shape) in block_shapes {
        out.push_str(&format!("    ({block_id}, &["));
        for (j, idx) in shape.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{idx}"));
        }
        out.push_str("]),\n");
    }
    out.push_str("];\n");
    out
}

#[cfg(test)]
mod drift_tests {
    use std::fs;
    use std::process::Command;

    use super::run;

    const GENERATED_FILES: [&str; 3] = ["block_properties.rs", "blocks.rs", "mod.rs"];

    /// The committed `src/generated/` is the golden artifact. Regenerate to a
    /// temp dir, rustfmt the temp copy (`phf::phf_map!` output is not
    /// format-clean as emitted), and assert byte-equality with what is
    /// committed. This enforces the no-drift guarantee without mutating
    /// repository source — a regeneration that changes output fails here until
    /// the new output is committed.
    #[test]
    fn generated_output_matches_committed() {
        let repo_root = crate::extract::find_repo_root().unwrap();
        let committed = repo_root.join("crates/rivet-registry/src/generated");
        let tmp = tempfile::tempdir().unwrap();
        let packets_tmp = tempfile::tempdir().unwrap();

        run(None, Some(tmp.path()), None, Some(packets_tmp.path())).unwrap();

        let files: Vec<_> = GENERATED_FILES.iter().map(|f| tmp.path().join(f)).collect();
        let status = Command::new("rustfmt")
            .args(["--edition", "2024"])
            .args(&files)
            .status()
            .expect("failed to run rustfmt");
        assert!(
            status.success(),
            "rustfmt failed on freshly generated output"
        );

        let mut committed_files: Vec<String> = fs::read_dir(&committed)
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        committed_files.sort();
        assert_eq!(
            committed_files, GENERATED_FILES,
            "committed src/generated/ has unexpected files"
        );

        for name in GENERATED_FILES {
            let generated = fs::read(tmp.path().join(name)).unwrap();
            let wanted = fs::read(committed.join(name)).unwrap();
            assert_eq!(
                generated, wanted,
                "generated output for {name} drifted from the committed golden copy; \
                 run `tools/rivet-codegen generate` and commit the result"
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::variant_name;

    #[test]
    fn variant_names_are_upper_camel() {
        assert_eq!(variant_name("axis", &[]), "Axis");
        assert_eq!(
            variant_name("creaking_heart_state", &[]),
            "CreakingHeartState"
        );
        assert_eq!(variant_name("waterlogged", &[]), "Waterlogged");
    }

    #[test]
    fn variant_name_collisions_get_suffix() {
        assert_eq!(variant_name("facing", &[]), "Facing");
        assert_eq!(variant_name("facing", &["Facing".to_string()]), "Facing2");
        assert_eq!(
            variant_name("facing", &["Facing".to_string(), "Facing2".to_string()]),
            "Facing3"
        );
    }
}
