//! `rivet-codegen generate` — read the extracted block-state JSON and emit Rust
//! registry source directly into `crates/rivet-registry/src/generated/`, and
//! consume the pinned `data/reports/packets.json` to emit the `rivet-protocol`
//! packet-ID tables (see [`crate::packets`]).

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::model::{BlockDef, BlockRegistry};

pub fn default_input(repo_root: &Path) -> PathBuf {
    repo_root.join("tools/rivet-codegen/data/block_states.json")
}

/// Generated tables are written directly into the `rivet-registry` crate so the
/// committed output cannot drift from what the generator produces.
pub fn default_output(repo_root: &Path) -> PathBuf {
    repo_root.join("crates/rivet-registry/src/generated")
}

pub fn run(
    input_flag: Option<&Path>,
    output_flag: Option<&Path>,
    packets_flag: Option<&Path>,
    packets_output_flag: Option<&Path>,
) -> Result<()> {
    let repo_root = crate::extract::find_repo_root()?;
    let output = match output_flag {
        Some(p) => p.to_path_buf(),
        None => default_output(&repo_root),
    };

    // The committed `src/generated/` dir holds several codegen-owned halves:
    // the extract-driven block tables (data/block_states.json), the
    // report-driven static-builtin tables (data/reports/registries.json), the
    // block-state global-id table (data/reports/blocks.json), the biome id
    // table + tag network content (data/biomes_tags.json), the block-behavior
    // table (data/block_behaviors.json), including the exact FULL-face support
    // masks, the worldgen noise/biome/preset data (data/worldgen.json), and
    // the packet tables (written into rivet-protocol
    // by packets::run). `mod.rs` declares the registry-owned ones and is
    // written last so it can never drift from the files it names.
    let block_version = run_blocks(input_flag, output_flag)?;
    crate::registries::run(None, Some(&output))?;
    crate::block_states::run(None, None, Some(&output))?;
    crate::biomes_tags::run(None, Some(&output))?;
    crate::block_behaviors::run(None, Some(&output))?;
    crate::synchronized::run(None, Some(&output))?;
    crate::registry_data::run(None, Some(&output))?;
    crate::worldgen::run(None, Some(&output))?;
    crate::feature_tables::run(None, Some(&output))?;
    crate::packets::run(packets_flag, packets_output_flag)?;

    let header = format!(
        "// Generated by `tools/rivet-codegen generate` from data/block_states.json +\n\
         // data/reports/registries.json + data/reports/blocks.json +\n\
         // data/biomes_tags.json + data/block_behaviors.json +\n\
         // data/worldgen.json + data/feature_data.json (MC {}).\n\
         // Do not edit by hand — PORTING.md: registries/data are generated, not hand-ported.\n\n",
        block_version
    );
    fs::create_dir_all(&output).with_context(|| format!("create {}", output.display()))?;
    fs::write(output.join("mod.rs"), format!("{header}{}", render_mod()))
        .context("write generated/mod.rs")?;
    Ok(())
}

fn run_blocks(input_flag: Option<&Path>, output_flag: Option<&Path>) -> Result<String> {
    let repo_root = crate::extract::find_repo_root()?;
    let input = match input_flag {
        Some(p) => p.to_path_buf(),
        None => default_input(&repo_root),
    };
    let output = match output_flag {
        Some(p) => p.to_path_buf(),
        None => default_output(&repo_root),
    };

    let data: BlockRegistry = serde_json::from_str(
        &fs::read_to_string(&input).with_context(|| format!("read {}", input.display()))?,
    )
    .with_context(|| format!("parse {}", input.display()))?;

    // Deduplicate (name, values) property types globally, preserving order of
    // first appearance. Ordering of values is preserved from the jar.
    let mut prop_index = HashMap::new();
    let mut prop_names: Vec<String> = Vec::new();
    let mut prop_values: Vec<Vec<String>> = Vec::new();
    let mut prop_variants: Vec<String> = Vec::new();

    let mut block_shapes: Vec<(u16, Vec<u16>)> = Vec::new();

    for block in &data.blocks {
        let mut shape: Vec<u16> = Vec::with_capacity(block.properties.len());
        for prop in &block.properties {
            let key = (prop.name.clone(), prop.values.clone());
            let idx = match prop_index.get(&key) {
                Some(&i) => i,
                None => {
                    let i = prop_names.len() as u16;
                    prop_index.insert(key.clone(), i);
                    prop_names.push(prop.name.clone());
                    prop_values.push(prop.values.clone());
                    prop_variants.push(variant_name(&prop.name, &prop_variants[..i as usize]));
                    i
                }
            };
            shape.push(idx);
        }
        if !shape.is_empty() {
            block_shapes.push((block.id, shape));
        }
    }

    fs::create_dir_all(&output).with_context(|| format!("create {}", output.display()))?;

    let header = format!(
        "// Generated by `tools/rivet-codegen generate` from data/block_states.json (MC {}).\n// Do not edit by hand — PORTING.md: registries/data are generated, not hand-ported.\n\n",
        data.minecraft_version
    );

    fs::write(
        output.join("blocks.rs"),
        format!("{header}{}", render_blocks(&data)?),
    )
    .context("write generated/blocks.rs")?;
    fs::write(
        output.join("block_properties.rs"),
        format!(
            "{header}{}",
            render_block_properties(&prop_names, &prop_values, &prop_variants, &block_shapes)
        ),
    )
    .context("write generated/block_properties.rs")?;

    let distinct_props = prop_names.len();
    println!(
        "Wrote {} blocks, {} distinct state-property types, {} per-block state shapes -> {}",
        data.blocks.len(),
        distinct_props,
        block_shapes.len(),
        output.display()
    );
    Ok(data.minecraft_version.clone())
}

/// The generated module file: declares the codegen-owned `src/generated/`
/// modules. `registries.rs` (the report-driven static-builtin tables),
/// `block_states.rs` (the report-driven block-state global-id table),
/// `biomes.rs`/`tags.rs` (the biome id table + tag network content),
/// `block_behaviors.rs` (the probe-driven per-StateId behavior table),
/// `synchronized.rs` (the configuration-sync element tables),
/// `registry_data.rs` (the pre-baked full NBT payloads), `worldgen.rs` (the
/// noise/biome-climate/preset data), and `feature_data.rs` (the seed-42 feature
/// tables) are added alongside the extract-driven block tables.
fn render_mod() -> String {
    "#[cfg(feature = \"blocks\")]\npub mod biomes;\n#[cfg(feature = \"blocks\")]\npub mod block_behaviors;\npub mod block_entity_types;\n#[cfg(feature = \"blocks\")]\npub mod block_properties;\n#[cfg(feature = \"blocks\")]\npub mod block_states;\n#[cfg(feature = \"blocks\")]\npub mod blocks;\n#[cfg(feature = \"blocks\")]\npub mod feature_data;\npub mod feature_size_types;\n#[cfg(feature = \"blocks\")]\npub mod registries;\n#[cfg(feature = \"blocks\")]\npub mod registry_data;\n#[cfg(feature = \"blocks\")]\npub mod synchronized;\n#[cfg(feature = \"blocks\")]\npub mod tags;\n#[cfg(feature = \"blocks\")]\npub mod worldgen;\n"
        .to_string()
}

/// `axis` -> `Axis`, `creaking_heart_state` -> `CreakingHeartState`. Appends a
/// numeric suffix (`Facing2`, `Facing3`) when the CamelCase name collides with
/// an earlier variant (a distinct `(name, values)` set sharing the same name).
fn variant_name(name: &str, existing: &[String]) -> String {
    let base = name
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect::<String>();
    if base.is_empty() {
        return "Property".to_string();
    }
    let mut candidate = base.clone();
    let mut n = 2;
    while existing.iter().any(|e| e == &candidate) {
        candidate = format!("{base}{n}");
        n += 1;
    }
    candidate
}

fn render_blocks(data: &BlockRegistry) -> Result<String> {
    // Sanity: registry ids must be contiguous 0..n for the id-indexed array.
    let mut ids: Vec<u16> = data.blocks.iter().map(|b| b.id).collect();
    ids.sort_unstable();
    for (i, id) in ids.iter().enumerate() {
        if *id as usize != i {
            bail!(
                "block registry ids are not contiguous (expected {} at index {i}); adjust the generator",
                id
            );
        }
    }

    // Emit in registry-id order so `BLOCK_BY_ID`'s id == index invariant holds
    // by construction, independent of the source JSON's block ordering.
    let mut blocks: Vec<&BlockDef> = data.blocks.iter().collect();
    blocks.sort_unstable_by_key(|b| b.id);

    let mut out = String::new();
    out.push_str("/// A numeric vanilla block id (index into the `minecraft:block` registry).\n");
    out.push_str("#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]\n");
    out.push_str("pub struct BlockId(pub u16);\n\n");

    out.push_str("/// Block name -> registry id.\n");
    out.push_str("pub static BLOCK_BY_NAME: phf::Map<&'static str, u16> = phf::phf_map! {\n");
    for b in &blocks {
        out.push_str(&format!("    {:?} => {}u16,\n", b.name, b.id));
    }
    out.push_str("};\n\n");

    out.push_str("/// Block names indexed by registry id (id == index).\n");
    out.push_str("pub static BLOCK_BY_ID: &[&str] = &[\n");
    for b in &blocks {
        out.push_str(&format!("    {:?}, // {}\n", b.name, b.id));
    }
    out.push_str("];\n\n");

    out.push_str("impl BlockId {\n");
    out.push_str(
        "    #[inline]\n    pub const fn from_id(id: u16) -> Self {\n        Self(id)\n    }\n\n",
    );
    out.push_str("    pub fn from_name(name: &str) -> Option<Self> {\n");
    out.push_str("        BLOCK_BY_NAME.get(name).copied().map(Self)\n    }\n\n");
    out.push_str("    pub fn name(self) -> &'static str {\n");
    out.push_str(
        "        BLOCK_BY_ID.get(self.0 as usize).copied().unwrap_or(\"minecraft:air\")\n    }\n\n",
    );
    out.push_str("    #[inline]\n    pub const fn id(self) -> u16 {\n        self.0\n    }\n}\n");

    Ok(out)
}

fn render_block_properties(
    prop_names: &[String],
    prop_values: &[Vec<String>],
    prop_variants: &[String],
    block_shapes: &[(u16, Vec<u16>)],
) -> String {
    let mut out = String::new();

    out.push_str("/// One distinct state-property type (a property name plus its\n");
    out.push_str("/// ordered value set, e.g. `axis: [x, y, z]`). Discriminant order\n");
    out.push_str("/// matches first appearance across the block registry.\n");
    out.push_str("#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]\n");
    out.push_str("#[repr(u16)]\n");
    out.push_str("pub enum BlockPropertyId {\n");
    for (i, v) in prop_variants.iter().enumerate() {
        let doc = format!(
            "    /// `{}`: [{}]",
            prop_names[i],
            prop_values[i].join(", ")
        );
        out.push_str(&format!("{doc}\n    {v} = {i},\n"));
    }
    out.push_str("}\n\n");

    out.push_str("/// Property name by `BlockPropertyId` discriminant.\n");
    out.push_str("pub static BLOCK_PROPERTY_NAMES: &[&str] = &[\n");
    for n in prop_names {
        out.push_str(&format!("    {n:?},\n"));
    }
    out.push_str("];\n\n");

    out.push_str("/// Ordered value sets by `BlockPropertyId` discriminant.\n");
    out.push_str("pub static BLOCK_PROPERTY_VALUES: &[&[&str]] = &[\n");
    for vals in prop_values {
        out.push_str("    &[");
        for (j, v) in vals.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{v:?}"));
        }
        out.push_str("],\n");
    }
    out.push_str("];\n\n");

    out.push_str("impl BlockPropertyId {\n");
    out.push_str("    /// The property id for a raw discriminant (e.g. an entry of a\n");
    out.push_str("    /// block's state shape), or `None` if `id` is outside\n");
    out.push_str("    /// `0..variant_count`. Fully safe: the discriminants are\n");
    out.push_str("    /// contiguous by construction.\n");
    out.push_str("    pub const fn from_id(id: u16) -> Option<Self> {\n");
    out.push_str("        match id {\n");
    for (i, v) in prop_variants.iter().enumerate() {
        out.push_str(&format!("            {i} => Some(Self::{v}),\n"));
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n    }\n\n");
    out.push_str("    pub fn name(self) -> &'static str {\n");
    out.push_str("        BLOCK_PROPERTY_NAMES[self as usize]\n    }\n\n");
    out.push_str("    pub fn values(self) -> &'static [&'static str] {\n");
    out.push_str("        BLOCK_PROPERTY_VALUES[self as usize]\n    }\n}\n\n");

    out.push_str(
        "/// Per-block state shape: `(block_id, &[property ids in declaration order])`.\n",
    );
    out.push_str("/// Blocks with no properties are omitted.\n");
    out.push_str("pub static BLOCK_STATE_SHAPES: &[(u16, &[u16])] = &[\n");
    for (block_id, shape) in block_shapes {
        out.push_str(&format!("    ({block_id}, &["));
        for (j, idx) in shape.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{idx}"));
        }
        out.push_str("]),\n");
    }
    out.push_str("];\n\n");

    // The largest per-block property shape. `BlockState`'s mixed-radix scratch
    // buffers are sized to this, so the bound is derived from the same table it
    // indexes and regenerates automatically if a future MC grows a shape.
    let max_shape_len = block_shapes.iter().map(|(_, s)| s.len()).max().unwrap_or(0);
    out.push_str(&format!(
        "/// The largest per-block property shape (max property count across all\n\
         /// blocks). Scratch buffers in `block_state::BlockState` are sized to this.\n\
         pub const MAX_BLOCK_STATE_PROPERTY_COUNT: usize = {max_shape_len};\n"
    ));
    out
}

#[cfg(test)]
mod drift_tests {
    use std::fs;
    use std::process::Command;

    use super::run;

    const GENERATED_FILES: [&str; 14] = [
        "biomes.rs",
        "block_behaviors.rs",
        "block_entity_types.rs",
        "block_properties.rs",
        "block_states.rs",
        "blocks.rs",
        "feature_data.rs",
        "feature_size_types.rs",
        "mod.rs",
        "registries.rs",
        "registry_data.rs",
        "synchronized.rs",
        "tags.rs",
        "worldgen.rs",
    ];

    /// The committed `src/generated/` is the golden artifact. Regenerate to a
    /// temp dir, rustfmt the temp copy (`phf::phf_map!` output is not
    /// format-clean as emitted), and assert byte-equality with what is
    /// committed. This enforces the no-drift guarantee without mutating
    /// repository source — a regeneration that changes output fails here until
    /// the new output is committed.
    #[test]
    fn generated_output_matches_committed() {
        let repo_root = crate::extract::find_repo_root().unwrap();
        let committed = repo_root.join("crates/rivet-registry/src/generated");
        let tmp = tempfile::tempdir().unwrap();
        let packets_tmp = tempfile::tempdir().unwrap();

        run(None, Some(tmp.path()), None, Some(packets_tmp.path())).unwrap();

        let files: Vec<_> = GENERATED_FILES.iter().map(|f| tmp.path().join(f)).collect();
        let status = Command::new("rustfmt")
            .args(["--edition", "2024"])
            .args(&files)
            .status()
            .expect("failed to run rustfmt");
        assert!(
            status.success(),
            "rustfmt failed on freshly generated output"
        );

        let mut committed_files: Vec<String> = fs::read_dir(&committed)
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        committed_files.sort();
        assert_eq!(
            committed_files, GENERATED_FILES,
            "committed src/generated/ has unexpected files"
        );

        for name in GENERATED_FILES {
            let generated = fs::read(tmp.path().join(name)).unwrap();
            let wanted = fs::read(committed.join(name)).unwrap();
            assert_eq!(
                generated, wanted,
                "generated output for {name} drifted from the committed golden copy; \
                 run `tools/rivet-codegen generate` and commit the result"
            );
        }
    }

    /// The report-driven `minecraft:block` surface and the extract-driven
    /// `data/block_states.json` are two independent captures of the same
    /// registry; they must agree (name set + ids). This is the provenance
    /// cross-check for the report-driven surfaces.
    #[test]
    fn report_block_surface_agrees_with_block_states_json() {
        let repo_root = crate::extract::find_repo_root().unwrap();
        let report = fs::read_to_string(crate::registries::default_input(&repo_root)).unwrap();
        let block_states = fs::read_to_string(crate::generate::default_input(&repo_root)).unwrap();

        let report_root: serde_json::Value = serde_json::from_str(&report).unwrap();
        let block_entries = &report_root["minecraft:block"]["entries"];
        let block_entries = block_entries.as_object().expect("block entries object");

        let block_states: crate::model::BlockRegistry =
            serde_json::from_str(&block_states).unwrap();

        let mut by_name: std::collections::HashMap<&str, u32> = block_entries
            .iter()
            .map(|(n, v)| {
                let id = v["protocol_id"].as_u64().expect("block protocol_id") as u32;
                (n.as_str(), id)
            })
            .collect();

        // The two sources must enumerate the same element set.
        let mut names = block_entries.keys().map(String::as_str).collect::<Vec<_>>();
        names.sort_unstable();
        let mut states = block_states
            .blocks
            .iter()
            .map(|b| b.name.as_str())
            .collect::<Vec<_>>();
        states.sort_unstable();
        assert_eq!(
            names, states,
            "report block set != block_states.json block set"
        );

        // And every id must agree.
        for block in &block_states.blocks {
            let report_id = by_name.remove(block.name.as_str()).expect("in both");
            assert_eq!(
                report_id, block.id as u32,
                "report/block_states id mismatch for {}",
                block.name
            );
        }
        assert!(by_name.is_empty(), "unmatched report entries");
    }

    /// The committed tables are codegen-owned; hand-mutating them must be
    /// caught by the drift test. Feed a deliberately-sparse `registries.json`
    /// to the report generator and require generation to fail rather than
    /// silently emit a broken table.
    #[test]
    fn sparse_report_fails_generation() {
        let repo_root = crate::extract::find_repo_root().unwrap();
        let tmp = tempfile::tempdir().unwrap();
        // A copy of the real fixture with one id removed makes the item
        // surface sparse.
        let input = repo_root.join(crate::registries::default_input(&repo_root));
        let mut value: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(&input).unwrap()).unwrap();
        let entries = value["minecraft:item"]["entries"].as_object_mut().unwrap();
        // Remove an interior element (id 100 of the dense 0..1536 surface) so
        // the remaining set has a hole at 100 while still containing ids above
        // and below it.
        let target = entries
            .iter()
            .find(|(_, v)| v["protocol_id"].as_u64() == Some(100))
            .map(|(k, _)| k.clone())
            .expect("interior item present");
        entries.remove(&target);
        let mutated = tmp.path().join("registries-mutated.json");
        fs::write(&mutated, serde_json::to_vec_pretty(&value).unwrap()).unwrap();
        // registries::run links the fixture to its provenance by reading the
        // sibling manifest.json; copy the committed manifest next to the
        // mutated fixture so only the mutation (not provenance) is under test.
        let manifest = input.parent().unwrap().join("manifest.json");
        fs::copy(&manifest, tmp.path().join("manifest.json")).unwrap();

        let err = crate::registries::run(Some(&mutated), Some(tmp.path())).unwrap_err();
        assert!(
            err.to_string().contains("not contiguous"),
            "sparse report must fail generation, got: {err}"
        );
    }

    /// Hand-inserting a duplicate id must fail generation (the reverse-table
    /// consistency check).
    #[test]
    fn duplicate_id_report_fails_generation() {
        let repo_root = crate::extract::find_repo_root().unwrap();
        let tmp = tempfile::tempdir().unwrap();
        let input = repo_root.join(crate::registries::default_input(&repo_root));
        let mut value: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(&input).unwrap()).unwrap();
        let entries = value["minecraft:item"]["entries"].as_object_mut().unwrap();
        // Clone an existing entry under a new name with the same protocol_id.
        let (first_name, first_entry) = entries.iter().next().unwrap();
        let cloned_name = format!("{first_name}_clone");
        entries.insert(cloned_name, first_entry.clone());
        let mutated = tmp.path().join("registries-mutated.json");
        fs::write(&mutated, serde_json::to_vec_pretty(&value).unwrap()).unwrap();
        // Same provenance linkage as the sparse test.
        let manifest = input.parent().unwrap().join("manifest.json");
        fs::copy(&manifest, tmp.path().join("manifest.json")).unwrap();

        let err = crate::registries::run(Some(&mutated), Some(tmp.path())).unwrap_err();
        assert!(
            err.to_string().contains("duplicate protocol_id"),
            "duplicate-id report must fail generation, got: {err}"
        );
    }
}

#[cfg(test)]
mod tests {
    use super::variant_name;

    #[test]
    fn variant_names_are_upper_camel() {
        assert_eq!(variant_name("axis", &[]), "Axis");
        assert_eq!(
            variant_name("creaking_heart_state", &[]),
            "CreakingHeartState"
        );
        assert_eq!(variant_name("waterlogged", &[]), "Waterlogged");
    }

    #[test]
    fn variant_name_collisions_get_suffix() {
        assert_eq!(variant_name("facing", &[]), "Facing");
        assert_eq!(variant_name("facing", &["Facing".to_string()]), "Facing2");
        assert_eq!(
            variant_name("facing", &["Facing".to_string(), "Facing2".to_string()]),
            "Facing3"
        );
    }
}
