//! `rivet-codegen mth-gen` — regenerate the Mth golden/sin-table files.
//!
//! The committed `crates/rivet-util/src/{mth_sin_table.rs, mth_atan_tables.rs,
//! mth_cos_tab_{x86_64,aarch64}.rs, mth_golden_tests.rs}` are
//! `GENERATED — do not hand-edit` but had no checked-in generator. This
//! subcommand produces them from the *real* Paper Mth class:
//!
//! 1. unpacks the bundler jar classpath (shared with `extract`);
//! 2. compiles a small Java helper (`java/MthGen.java`, itself generated by
//!    `scripts/gen_mth_gen.py` from `data/mth_vectors.tsv`) against it;
//! 3. runs the helper and reads back:
//!      - the 65536-entry `SIN` table,
//!      - the 257-entry `ASIN_TAB` and the host-arch `COS_TAB` table,
//!      - the 1156 golden vectors (each Mth call recomputed via the real class,
//!        NaN-canonicalized per D14 via floatToIntBits/doubleToLongBits);
//! 4. emits the `.rs` files by substituting values into the committed
//!    structure (`data/mth_golden_skeleton.rs` for the golden file, the known
//!    table layout for the table files), then pipes through `rustfmt`
//!    so the result matches the committed files byte-for-byte (they are
//!    rustfmt-idempotent, verified).
//!
//! COS_TAB is arch-dependent (D14): only the HOST arch's module is written.
//! On x86_64 (the primary release-gate target) this writes
//! `mth_cos_tab_x86_64.rs`; the committed `mth_cos_tab_aarch64.rs` is
//! provenance-checked — it is generated and verified on native aarch64 and is
//! never substituted or silently overwritten by an x86_64 run. On an aarch64
//! host, the aarch64 module is (re)generated idempotently from native Paper.
//!
//! Regeneration is idempotent per arch: running it over the current committed
//! files reproduces them exactly on the matching host (`git diff` stays clean).

use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, anyhow, bail};

use crate::extract;

/// Repo-relative paths of the generated files.
const GOLDEN_REL: &str = "crates/rivet-util/src/mth_golden_tests.rs";
const SIN_REL: &str = "crates/rivet-util/src/mth_sin_table.rs";
const ATAN_REL: &str = "crates/rivet-util/src/mth_atan_tables.rs";
/// Per-arch COS_TAB modules (D14). COS_TAB differs by up to 1 ULP between
/// x86_64 and aarch64 because Paper builds it at class-init with
/// java.lang.Math.cos/asin whose HotSpot intrinsics are arch-dependent. Each
/// arch's table is generated independently on that platform.
const COS_X86_REL: &str = "crates/rivet-util/src/mth_cos_tab_x86_64.rs";
const COS_A64_REL: &str = "crates/rivet-util/src/mth_cos_tab_aarch64.rs";

pub fn run(bundler_flag: Option<&Path>, output_flag: Option<&Path>) -> Result<()> {
    let repo_root = extract::find_repo_root()?;
    let bundler = match bundler_flag {
        Some(p) => p.to_path_buf(),
        None => extract::default_bundler(&repo_root),
    };
    anyhow::ensure!(
        bundler.is_file(),
        "bundler jar not found at {} — pass --bundler or build Paper first",
        bundler.display()
    );

    let out_dir = match output_flag {
        Some(p) => p.to_path_buf(),
        None => repo_root.clone(),
    };
    fs::create_dir_all(&out_dir).with_context(|| format!("create {}", out_dir.display()))?;

    let (classpath, java, javac) = extract::prepare_runtime(&repo_root, &bundler)?;

    // Compile the Java oracle (generated by scripts/gen_mth_gen.py).
    let cache = repo_root.join("tools/rivet-codegen/.cache");
    let helper_dir = cache.join("mthhelper");
    fs::create_dir_all(&helper_dir)?;
    let helper_src = include_str!("java/MthGen.java");
    let helper_file = helper_dir.join("MthGen.java");
    fs::write(&helper_file, helper_src).context("write MthGen.java")?;
    let helper_dir_arg = extract::path_to_utf8(&helper_dir, "MthGen output directory")?;
    let helper_file_arg = extract::path_to_utf8(&helper_file, "MthGen source")?;
    extract::run_cmd(
        &javac,
        &["-cp", &classpath, "-d", helper_dir_arg, helper_file_arg],
        "compile MthGen.java",
    )?;

    // Quiet log4j down so stdout only carries the oracle's table/vector lines.
    let log4j_off = cache.join("log4j2-off.xml");
    fs::write(
        &log4j_off,
        r#"<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="off"><Loggers><Root level="off"/></Loggers></Configuration>
"#,
    )
    .context("write log4j2-off.xml")?;

    let helper_dir_arg = crate::extract::path_to_utf8(&helper_dir, "MthGen classpath directory")?;
    let classpath_arg = format!("{classpath}:{helper_dir_arg}");
    let log4j_arg = format!(
        "-Dlog4j.configurationFile={}",
        crate::extract::path_to_utf8(&log4j_off, "log4j configuration")?
    );
    let out = extract::run_cmd_capture(
        &java,
        &[
            "-cp",
            &classpath_arg,
            "--enable-native-access=ALL-UNNAMED",
            &log4j_arg,
            "MthGen",
        ],
        "run MthGen",
    )?;

    let parsed = parse_oracle_output(&out)?;

    let golden_out = out_dir.join(GOLDEN_REL);
    if let Some(dir) = golden_out.parent() {
        fs::create_dir_all(dir).with_context(|| format!("create {}", dir.display()))?;
    }
    fs::write(
        &golden_out,
        render_golden(&repo_root, &parsed.vectors).context("render golden")?,
    )
    .with_context(|| format!("write {}", golden_out.display()))?;

    let sin_out = out_dir.join(SIN_REL);
    fs::write(&sin_out, render_sin(&parsed.sin))
        .with_context(|| format!("write {}", sin_out.display()))?;

    let atan_out = out_dir.join(ATAN_REL);
    fs::write(&atan_out, render_asin(&parsed.asin))
        .with_context(|| format!("write {}", atan_out.display()))?;

    // Write the COS_TAB module for the *host* architecture only. x86_64 (the
    // primary release-gate target, D14) regenerates mth_cos_tab_x86_64.rs; the
    // committed aarch64 variant is provenance-checked — it is generated and
    // verified on native aarch64 and must NEVER be substituted or silently
    // overwritten by an x86_64 run. On an aarch64 host this path writes the
    // aarch64 module (and idempotently reproduces the committed aarch64 table
    // from native Paper).
    let (cos_rel, cos_label) = if cfg!(target_arch = "aarch64") {
        (COS_A64_REL, "aarch64")
    } else {
        (COS_X86_REL, "x86_64")
    };
    let cos_out = out_dir.join(cos_rel);
    fs::write(&cos_out, render_cos(&parsed.cos, cos_label))
        .with_context(|| format!("write {}", cos_out.display()))?;

    println!(
        "Wrote {} ({} vectors), {} ({} entries), {} ({} ASIN entries), {} ({} COS entries, {})",
        golden_out.display(),
        parsed.vectors.len(),
        sin_out.display(),
        parsed.sin.len(),
        atan_out.display(),
        parsed.asin.len(),
        cos_out.display(),
        parsed.cos.len(),
        cos_label
    );
    Ok(())
}

struct OracleOutput {
    sin: Vec<String>,
    asin: Vec<String>,
    cos: Vec<String>,
    vectors: Vec<String>,
}

fn parse_oracle_output(out: &str) -> Result<OracleOutput> {
    let mut sin = Vec::new();
    let mut asin = Vec::new();
    let mut cos = Vec::new();
    let mut vectors = Vec::new();
    let mut section: Option<&str> = None;
    for line in out.lines() {
        match line {
            "SIN_TAB_START" => section = Some("sin"),
            "ASIN_TAB_START" => section = Some("asin"),
            "COS_TAB_START" => section = Some("cos"),
            "VECTORS_START" => section = Some("vec"),
            _ => match section {
                Some("sin") => sin.push(line.to_string()),
                Some("asin") => asin.push(line.to_string()),
                Some("cos") => cos.push(line.to_string()),
                Some("vec") => vectors.push(line.to_string()),
                _ => bail!("unexpected line before any section marker: {line:?}"),
            },
        }
    }
    anyhow::ensure!(
        sin.len() == 65536,
        "SIN table has {} entries, expected 65536",
        sin.len()
    );
    anyhow::ensure!(
        asin.len() == 257,
        "ASIN_TAB has {} entries, expected 257",
        asin.len()
    );
    anyhow::ensure!(
        cos.len() == 257,
        "COS_TAB has {} entries, expected 257",
        cos.len()
    );
    anyhow::ensure!(
        vectors.len() == 1156,
        "golden vectors: {} expected 1156",
        vectors.len()
    );
    Ok(OracleOutput {
        sin,
        asin,
        cos,
        vectors,
    })
}

/// Render mth_sin_table.rs — header + `f32::from_bits(...)` per entry.
fn render_sin(sin: &[String]) -> String {
    let mut s = String::new();
    s.push_str("#![allow(clippy::large_const_arrays)]\n");
    s.push_str("// GENERATED from net.minecraft.util.Mth (working/Paper) — do not hand-edit.\n");
    s.push_str("// Table: SIN[i] = (float)Math.sin(i / 10430.378350470453), i in [0,65536).\n");
    s.push_str("pub const SIN: [f32; 65536] = [\n");
    for v in sin {
        s.push_str("    f32::from_bits(");
        s.push_str(v);
        s.push_str("),\n");
    }
    s.push_str("];\n");
    s
}

/// Render mth_atan_tables.rs — ASIN_TAB (arch-independent) plus the
/// compile-time COS_TAB selector (D14).
fn render_asin(asin: &[String]) -> String {
    let mut s = String::new();
    s.push_str("// GENERATED from net.minecraft.util.Mth (working/Paper) — do not hand-edit.\n");
    s.push_str("// ASIN_TAB[ind] = Math.asin(ind/256.0); ind in [0,257).\n");
    s.push_str("//\n");
    s.push_str("// COS_TAB is architecture-dependent (D14): Paper 26.2 builds the tables at\n");
    s.push_str("// class-init with java.lang.Math.cos/asin, whose HotSpot intrinsics differ by\n");
    s.push_str("// up to 1 ULP between x86_64 and aarch64. ASIN_TAB is identical on both\n");
    s.push_str("// supported arches; COS_TAB is selected at COMPILE TIME from the per-arch\n");
    s.push_str("// generated module matching the build target. Each arch's table is generated\n");
    s.push_str("// independently on that platform via the codegen path — never hand-edited,\n");
    s.push_str("// never substituted.\n");
    s.push_str("pub const ASIN_TAB: [f64; 257] = [\n");
    for v in asin {
        s.push_str("    f64::from_bits(");
        s.push_str(v);
        s.push_str("),\n");
    }
    s.push_str("];\n");
    s.push('\n');
    s.push_str("#[cfg(target_arch = \"aarch64\")]\n");
    s.push_str("pub use super::mth_cos_tab_aarch64::COS_TAB;\n");
    s.push_str("/// Architecture-selected COS_TAB (D14). x86_64 Linux + Temurin 25 is the\n");
    s.push_str("/// primary release-gate target; aarch64 retains its own verified table.\n");
    s.push_str("#[cfg(target_arch = \"x86_64\")]\n");
    s.push_str("pub use super::mth_cos_tab_x86_64::COS_TAB;\n");
    s.push_str("#[cfg(not(any(target_arch = \"x86_64\", target_arch = \"aarch64\")))]\n");
    s.push_str("compile_error!(\n");
    s.push_str("    \"Rivet supports COS_TAB parity on x86_64 and aarch64 only; add native Paper Mth parity for this arch (D14)\"\n");
    s.push_str(");\n");
    s
}

/// Render one per-arch COS_TAB module (mth_cos_tab_{x86_64,aarch64}.rs).
fn render_cos(cos: &[String], arch_label: &str) -> String {
    let mut s = String::new();
    s.push_str("// GENERATED from net.minecraft.util.Mth (working/Paper) — do not hand-edit.\n");
    s.push_str("// COS_TAB[");
    s.push_str(arch_label);
    s.push_str("][ind] = Math.cos(Math.asin(ind/256.0)) on native ");
    s.push_str(arch_label);
    s.push_str(" Paper (D14),\n");
    s.push_str("// ind in [0,257). Generated by `rivet-codegen mth-gen` on the host arch.\n");
    if arch_label == "aarch64" {
        s.push_str("// PROVENANCE: generated + verified on native aarch64 Paper/Temurin. Never\n");
        s.push_str("// overwritten by an x86_64 mth-gen run; only an aarch64 codegen path may\n");
        s.push_str("// regenerate it.\n");
    } else {
        s.push_str("// PROVENANCE: generated on x86_64 Linux + Temurin 25 (primary release-gate\n");
        s.push_str("// target, D14).\n");
    }
    s.push_str("pub const COS_TAB: [f64; 257] = [\n");
    for v in cos {
        s.push_str("    f64::from_bits(");
        s.push_str(v);
        s.push_str("),\n");
    }
    s.push_str("];\n");
    s
}

/// Substitute vector values into the committed golden skeleton, then rustfmt.
fn render_golden(repo_root: &Path, vectors: &[String]) -> Result<String> {
    let skeleton_path = repo_root.join("tools/rivet-codegen/data/mth_golden_skeleton.rs");
    let skeleton = fs::read_to_string(&skeleton_path)
        .with_context(|| format!("read skeleton {}", skeleton_path.display()))?;

    let mut filled = skeleton.clone();
    for (i, v) in vectors.iter().enumerate() {
        let ph = format!("@@{i}@@");
        let count = filled.matches(&ph).count();
        anyhow::ensure!(
            count == 1,
            "placeholder {ph} occurs {count} times in skeleton"
        );
        filled = filled.replace(&ph, v);
    }
    anyhow::ensure!(
        !filled.contains("@@"),
        "unfilled placeholders remain in golden output"
    );

    rustfmt(repo_root, &filled).with_context(|| "rustfmt golden tests")
}

/// Pipe source through rustfmt (the repo toolchain) for canonical formatting.
fn rustfmt(repo_root: &Path, src: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .current_dir(repo_root)
        .spawn()
        .context("spawn rustfmt")?;
    use std::io::Write;
    child
        .stdin
        .as_mut()
        .ok_or_else(|| anyhow!("no stdin on rustfmt"))?
        .write_all(src.as_bytes())
        .context("write to rustfmt stdin")?;
    let out = child.wait_with_output().context("wait rustfmt")?;
    if !out.status.success() {
        bail!(
            "rustfmt failed: {}\n{}",
            out.status,
            String::from_utf8_lossy(&out.stderr)
        );
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}
