//! `rivet-codegen mth-gen` — regenerate the Mth golden/sin-table files.
//!
//! The committed `crates/rivet-util/src/{mth_sin_table.rs, mth_atan_tables.rs,
//! mth_cos_tab_{x86_64,aarch64}.rs, mth_golden_tests.rs}` are
//! `GENERATED — do not hand-edit` but had no checked-in generator. This
//! subcommand produces them from the *real* Paper Mth class:
//!
//! 1. unpacks the bundler jar classpath (shared with `extract`);
//! 2. compiles a small Java helper (`java/MthGen.java`, itself generated by
//!    `scripts/gen_mth_gen.py` from `data/mth_vectors.tsv`) against it;
//! 3. runs the helper and reads back:
//!      - the 65536-entry `SIN` table,
//!      - the 257-entry `ASIN_TAB` and the host-arch `COS_TAB` table,
//!      - the 1156 golden vectors (each Mth call recomputed via the real class,
//!        NaN-canonicalized per D14 via floatToIntBits/doubleToLongBits);
//! 4. emits the `.rs` files by substituting values into the committed
//!    structure (`data/mth_golden_skeleton.rs` for the golden file, the known
//!    table layout for the table files), then pipes through `rustfmt`
//!    so the result matches the committed files byte-for-byte (they are
//!    rustfmt-idempotent, verified).
//!
//! COS_TAB is arch-dependent (D14): only the HOST arch's module is written.
//! On x86_64 (the primary release-gate target) this writes
//! `mth_cos_tab_x86_64.rs`; the committed `mth_cos_tab_aarch64.rs` is
//! provenance-checked — it is generated and verified on native aarch64 and is
//! never substituted or silently overwritten by an x86_64 run. On an aarch64
//! host, the aarch64 module is (re)generated idempotently from native Paper.
//!
//! Regeneration is idempotent per arch: running it over the current committed
//! files reproduces them exactly on the matching host (`git diff` stays clean).

use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, anyhow, bail};

use crate::extract;

/// Repo-relative paths of the generated files.
const GOLDEN_REL: &str = "crates/rivet-util/src/mth_golden_tests.rs";
const SIN_REL: &str = "crates/rivet-util/src/mth_sin_table.rs";
const ATAN_REL: &str = "crates/rivet-util/src/mth_atan_tables.rs";
/// Per-arch COS_TAB modules (D14). COS_TAB differs by up to 1 ULP between
/// x86_64 and aarch64 because Paper builds it at class-init with
/// java.lang.Math.cos/asin whose HotSpot intrinsics are arch-dependent. Each
/// arch's table is generated independently on that platform.
const COS_X86_REL: &str = "crates/rivet-util/src/mth_cos_tab_x86_64.rs";
const COS_A64_REL: &str = "crates/rivet-util/src/mth_cos_tab_aarch64.rs";

pub fn run(bundler_flag: Option<&Path>, output_flag: Option<&Path>) -> Result<()> {
    let repo_root = extract::find_repo_root()?;
    let bundler = match bundler_flag {
        Some(p) => p.to_path_buf(),
        None => extract::default_bundler(&repo_root),
    };
    anyhow::ensure!(
        bundler.is_file(),
        "bundler jar not found at {} — pass --bundler or build Paper first",
        bundler.display()
    );

    let out_dir = match output_flag {
        Some(p) => p.to_path_buf(),
        None => repo_root.clone(),
    };
    fs::create_dir_all(&out_dir).with_context(|| format!("create {}", out_dir.display()))?;

    let (classpath, java, javac) = extract::prepare_runtime(&repo_root, &bundler)?;

    // Compile the Java oracle (generated by scripts/gen_mth_gen.py).
    let cache = repo_root.join("tools/rivet-codegen/.cache");
    let helper_dir = cache.join("mthhelper");
    fs::create_dir_all(&helper_dir)?;
    let helper_src = include_str!("java/MthGen.java");
    let helper_file = helper_dir.join("MthGen.java");
    fs::write(&helper_file, helper_src).context("write MthGen.java")?;
    let helper_dir_arg = extract::path_to_utf8(&helper_dir, "MthGen output directory")?;
    let helper_file_arg = extract::path_to_utf8(&helper_file, "MthGen source")?;
    extract::run_cmd(
        &javac,
        &["-cp", &classpath, "-d", helper_dir_arg, helper_file_arg],
        "compile MthGen.java",
    )?;

    // Quiet log4j down so stdout only carries the oracle's table/vector lines.
    let log4j_off = cache.join("log4j2-off.xml");
    fs::write(
        &log4j_off,
        r#"<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="off"><Loggers><Root level="off"/></Loggers></Configuration>
"#,
    )
    .context("write log4j2-off.xml")?;

    let helper_dir_arg = crate::extract::path_to_utf8(&helper_dir, "MthGen classpath directory")?;
    let classpath_arg = format!("{classpath}:{helper_dir_arg}");
    let log4j_arg = format!(
        "-Dlog4j.configurationFile={}",
        crate::extract::path_to_utf8(&log4j_off, "log4j configuration")?
    );
    let out = extract::run_cmd_capture(
        &java,
        &[
            "-cp",
            &classpath_arg,
            "--enable-native-access=ALL-UNNAMED",
            &log4j_arg,
            "MthGen",
        ],
        "run MthGen",
    )?;

    let parsed = parse_oracle_output(&out)?;

    let golden_out = out_dir.join(GOLDEN_REL);
    if let Some(dir) = golden_out.parent() {
        fs::create_dir_all(dir).with_context(|| format!("create {}", dir.display()))?;
    }
    let rendered = render_golden(&repo_root, &parsed.vectors).context("render golden")?;
    fs::write(&golden_out, &rendered).with_context(|| format!("write {}", golden_out.display()))?;

    // Fail-closed cross-check (D14): the four arch-selected atan2 rows read
    // COS_TAB[181], which differs between x86_64 and aarch64 by 1 ULP. Verify
    // the aarch64 expected bits asserted in the rendered golden equal what
    // faithful atan2 arithmetic over the *committed* aarch64 COS_TAB produces,
    // so the aarch64 branch can never silently drift from its provenance table.
    verify_arch_selected_aarch64_bits(&repo_root, &rendered)
        .context("arch-selected aarch64 golden cross-check")?;

    let sin_out = out_dir.join(SIN_REL);
    fs::write(&sin_out, render_sin(&parsed.sin))
        .with_context(|| format!("write {}", sin_out.display()))?;

    let atan_out = out_dir.join(ATAN_REL);
    fs::write(&atan_out, render_asin(&parsed.asin))
        .with_context(|| format!("write {}", atan_out.display()))?;

    // Write the COS_TAB module for the *host* architecture only. x86_64 (the
    // primary release-gate target, D14) regenerates mth_cos_tab_x86_64.rs; the
    // committed aarch64 variant is provenance-checked — it is generated and
    // verified on native aarch64 and must NEVER be substituted or silently
    // overwritten by an x86_64 run. On an aarch64 host this path writes the
    // aarch64 module (and idempotently reproduces the committed aarch64 table
    // from native Paper).
    let (cos_rel, cos_label) = if cfg!(target_arch = "aarch64") {
        (COS_A64_REL, "aarch64")
    } else {
        (COS_X86_REL, "x86_64")
    };
    let cos_out = out_dir.join(cos_rel);
    fs::write(&cos_out, render_cos(&parsed.cos, cos_label))
        .with_context(|| format!("write {}", cos_out.display()))?;

    println!(
        "Wrote {} ({} vectors), {} ({} entries), {} ({} ASIN entries), {} ({} COS entries, {})",
        golden_out.display(),
        parsed.vectors.len(),
        sin_out.display(),
        parsed.sin.len(),
        atan_out.display(),
        parsed.asin.len(),
        cos_out.display(),
        parsed.cos.len(),
        cos_label
    );
    Ok(())
}

struct OracleOutput {
    sin: Vec<String>,
    asin: Vec<String>,
    cos: Vec<String>,
    vectors: Vec<String>,
}

fn parse_oracle_output(out: &str) -> Result<OracleOutput> {
    let mut sin = Vec::new();
    let mut asin = Vec::new();
    let mut cos = Vec::new();
    let mut vectors = Vec::new();
    let mut section: Option<&str> = None;
    for line in out.lines() {
        match line {
            "SIN_TAB_START" => section = Some("sin"),
            "ASIN_TAB_START" => section = Some("asin"),
            "COS_TAB_START" => section = Some("cos"),
            "VECTORS_START" => section = Some("vec"),
            _ => match section {
                Some("sin") => sin.push(line.to_string()),
                Some("asin") => asin.push(line.to_string()),
                Some("cos") => cos.push(line.to_string()),
                Some("vec") => vectors.push(line.to_string()),
                _ => bail!("unexpected line before any section marker: {line:?}"),
            },
        }
    }
    anyhow::ensure!(
        sin.len() == 65536,
        "SIN table has {} entries, expected 65536",
        sin.len()
    );
    anyhow::ensure!(
        asin.len() == 257,
        "ASIN_TAB has {} entries, expected 257",
        asin.len()
    );
    anyhow::ensure!(
        cos.len() == 257,
        "COS_TAB has {} entries, expected 257",
        cos.len()
    );
    anyhow::ensure!(
        vectors.len() == 1156,
        "golden vectors: {} expected 1156",
        vectors.len()
    );
    Ok(OracleOutput {
        sin,
        asin,
        cos,
        vectors,
    })
}

/// Render mth_sin_table.rs — header + `f32::from_bits(...)` per entry.
fn render_sin(sin: &[String]) -> String {
    let mut s = String::new();
    s.push_str("#![allow(clippy::large_const_arrays)]\n");
    s.push_str("// GENERATED from net.minecraft.util.Mth (working/Paper) — do not hand-edit.\n");
    s.push_str("// Table: SIN[i] = (float)Math.sin(i / 10430.378350470453), i in [0,65536).\n");
    s.push_str("pub const SIN: [f32; 65536] = [\n");
    for v in sin {
        s.push_str("    f32::from_bits(");
        s.push_str(v);
        s.push_str("),\n");
    }
    s.push_str("];\n");
    s
}

/// Render mth_atan_tables.rs — ASIN_TAB (arch-independent) plus the
/// compile-time COS_TAB selector (D14).
fn render_asin(asin: &[String]) -> String {
    let mut s = String::new();
    s.push_str("// GENERATED from net.minecraft.util.Mth (working/Paper) — do not hand-edit.\n");
    s.push_str("// ASIN_TAB[ind] = Math.asin(ind/256.0); ind in [0,257).\n");
    s.push_str("//\n");
    s.push_str("// COS_TAB is architecture-dependent (D14): Paper 26.2 builds the tables at\n");
    s.push_str("// class-init with java.lang.Math.cos/asin, whose HotSpot intrinsics differ by\n");
    s.push_str("// up to 1 ULP between x86_64 and aarch64. ASIN_TAB is identical on both\n");
    s.push_str("// supported arches; COS_TAB is selected at COMPILE TIME from the per-arch\n");
    s.push_str("// generated module matching the build target. Each arch's table is generated\n");
    s.push_str("// independently on that platform via the codegen path — never hand-edited,\n");
    s.push_str("// never substituted.\n");
    s.push_str("pub const ASIN_TAB: [f64; 257] = [\n");
    for v in asin {
        s.push_str("    f64::from_bits(");
        s.push_str(v);
        s.push_str("),\n");
    }
    s.push_str("];\n");
    s.push('\n');
    s.push_str("#[cfg(target_arch = \"aarch64\")]\n");
    s.push_str("pub use super::mth_cos_tab_aarch64::COS_TAB;\n");
    s.push_str("/// Architecture-selected COS_TAB (D14). x86_64 Linux + Temurin 25 is the\n");
    s.push_str("/// primary release-gate target; aarch64 retains its own verified table.\n");
    s.push_str("#[cfg(target_arch = \"x86_64\")]\n");
    s.push_str("pub use super::mth_cos_tab_x86_64::COS_TAB;\n");
    s.push_str("#[cfg(not(any(target_arch = \"x86_64\", target_arch = \"aarch64\")))]\n");
    s.push_str("compile_error!(\n");
    s.push_str("    \"Rivet supports COS_TAB parity on x86_64 and aarch64 only; add native Paper Mth parity for this arch (D14)\"\n");
    s.push_str(");\n");
    s
}

/// Render one per-arch COS_TAB module (mth_cos_tab_{x86_64,aarch64}.rs).
fn render_cos(cos: &[String], arch_label: &str) -> String {
    let mut s = String::new();
    s.push_str("// GENERATED from net.minecraft.util.Mth (working/Paper) — do not hand-edit.\n");
    s.push_str("// COS_TAB[");
    s.push_str(arch_label);
    s.push_str("][ind] = Math.cos(Math.asin(ind/256.0)) on native ");
    s.push_str(arch_label);
    s.push_str(" Paper (D14),\n");
    s.push_str("// ind in [0,257). Generated by `rivet-codegen mth-gen` on the host arch.\n");
    if arch_label == "aarch64" {
        s.push_str("// PROVENANCE: generated + verified on native aarch64 Paper/Temurin. Never\n");
        s.push_str("// overwritten by an x86_64 mth-gen run; only an aarch64 codegen path may\n");
        s.push_str("// regenerate it.\n");
    } else {
        s.push_str("// PROVENANCE: generated on x86_64 Linux + Temurin 25 (primary release-gate\n");
        s.push_str("// target, D14).\n");
    }
    s.push_str("pub const COS_TAB: [f64; 257] = [\n");
    for v in cos {
        s.push_str("    f64::from_bits(");
        s.push_str(v);
        s.push_str("),\n");
    }
    s.push_str("];\n");
    s
}

/// Substitute vector values into the committed golden skeleton, then rustfmt.
fn render_golden(repo_root: &Path, vectors: &[String]) -> Result<String> {
    let skeleton_path = repo_root.join("tools/rivet-codegen/data/mth_golden_skeleton.rs");
    let skeleton = fs::read_to_string(&skeleton_path)
        .with_context(|| format!("read skeleton {}", skeleton_path.display()))?;

    let mut filled = skeleton.clone();
    for (i, v) in vectors.iter().enumerate() {
        let ph = format!("@@{i}@@");
        let count = filled.matches(&ph).count();
        anyhow::ensure!(
            count == 1,
            "placeholder {ph} occurs {count} times in skeleton"
        );
        filled = filled.replace(&ph, v);
    }
    anyhow::ensure!(
        !filled.contains("@@"),
        "unfilled placeholders remain in golden output"
    );

    rustfmt(repo_root, &filled).with_context(|| "rustfmt golden tests")
}

/// The four golden `atan2` rows whose expected value is arch-selected (D14):
/// `(y, x)` and the placeholder index. Each reads COS_TAB[181], whose x86_64
/// and aarch64 values differ by 1 ULP, so the same (y, x) yields a different
/// last mantissa bit per arch. Both arches' expected bits must come from their
/// own committed COS_TAB — never hand-hard-coded inconsistently.
///
/// `want` is the aarch64 expected magnitude bits (from the committed aarch64
/// COS_TAB via faithful atan2); the generator verifies the rendered golden
/// asserts exactly these for the aarch64 branch. The needle strings mirror the
/// Rust literals emitted in the golden (`1.0`, `-1.0`, `0.5`, `-0.5`).
const ARCH_SELECTED_ATAN2: [(usize, f64, f64, &str); 4] = [
    (547, 1.0, 1.0, "super::atan2(1.0, 1.0)"),
    (550, -1.0, 1.0, "super::atan2(-1.0, 1.0)"),
    (565, 0.5, 0.5, "super::atan2(0.5, 0.5)"),
    (566, -0.5, 0.5, "super::atan2(-0.5, 0.5)"),
];

/// Faithful `Mth.atan2` (fast inverse sqrt + 257-entry LUT), mirroring
/// `crates/rivet-util/src/mth.rs::atan2` but parameterized on the COS_TAB so
/// the generator can derive per-arch expected bits from each committed table.
/// Passed ASIN is arch-independent and identical on both arches.
fn faithful_atan2(y0: f64, x0: f64, asin: &[f64; 257], cos: &[f64; 257]) -> f64 {
    let mut y = y0;
    let mut x = x0;
    let d2 = x * x + y * y;
    if d2.is_nan() {
        return f64::NAN;
    }
    let neg_y = y < 0.0;
    if neg_y {
        y = -y;
    }
    let neg_x = x < 0.0;
    if neg_x {
        x = -x;
    }
    let steep = y > x;
    if steep {
        // Java's `t = x; x = y; y = t` kept verbatim (see `atan2` doc).
        #[allow(clippy::manual_swap)]
        {
            let t = x;
            x = y;
            y = t;
        }
    }
    let rinv = faithful_fast_inv_sqrt(d2);
    x *= rinv;
    y *= rinv;
    let yp = FRAC_BIAS + y;
    let index = ((yp.to_bits() as i64) as i32) as usize;
    let phi = asin[index];
    let c_phi = cos[index];
    let s_phi = yp - FRAC_BIAS;
    let sd = y * c_phi - x * s_phi;
    let d = (6.0 + sd * sd) * sd * 0.16666666666666666;
    let mut theta = phi + d;
    if steep {
        theta = std::f64::consts::FRAC_PI_2 - theta;
    }
    if neg_x {
        theta = std::f64::consts::PI - theta;
    }
    if neg_y {
        theta = -theta;
    }
    theta
}

fn faithful_fast_inv_sqrt(mut x: f64) -> f64 {
    let xhalf = 0.5 * x;
    let mut i = x.to_bits() as i64;
    i = 6910469410427058090i64.wrapping_sub(i >> 1);
    x = f64::from_bits(i as u64);
    x * (1.5 - xhalf * x * x)
}

const FRAC_BIAS: f64 = f64::from_bits(0x42b0000000000000);

/// Parse a committed `[f64; 257]` table file (`f64::from_bits(0x...)` rows).
fn read_f64_table_257(repo_root: &Path, rel: &str) -> Result<[f64; 257]> {
    let path = repo_root.join(rel);
    let src =
        fs::read_to_string(&path).with_context(|| format!("read table {}", path.display()))?;
    let mut out = [0.0f64; 257];
    let mut n = 0;
    for line in src.lines() {
        let hex = line.split("0x").nth(1).and_then(|s| s.split(')').next());
        let Some(hex) = hex else { continue };
        let hex = hex.trim_start_matches("0x").trim();
        if hex.is_empty() || !hex.chars().all(|c| c.is_ascii_hexdigit()) {
            continue;
        }
        anyhow::ensure!(n < out.len(), "{rel}: expected 257 entries, found more");
        let bits = u64::from_str_radix(hex, 16).context("parse f64 bits")?;
        out[n] = f64::from_bits(bits);
        n += 1;
    }
    anyhow::ensure!(n == 257, "{rel}: expected 257 entries, found {n}");
    Ok(out)
}

/// Double-to-long-bits (canonicalize NaN like `Double.doubleToLongBits`, D14).
fn d2l(v: f64) -> u64 {
    if v.is_nan() {
        0x7ff8_0000_0000_0000
    } else {
        v.to_bits()
    }
}

/// Verify the aarch64 branch of each arch-selected golden row matches the
/// faithful atan2 result over the committed aarch64 COS_TAB (+ ASIN). Fails
/// closed so a stale/mismatched aarch64 literal is caught at generation time.
fn verify_arch_selected_aarch64_bits(repo_root: &Path, rendered: &str) -> Result<()> {
    let asin = read_f64_table_257(repo_root, ATAN_REL)?;
    let cos_a64 = read_f64_table_257(repo_root, COS_A64_REL)?;

    for &(idx, y, x, needle) in &ARCH_SELECTED_ATAN2 {
        // Full canonical double-to-long bits (includes the sign bit, matching
        // the asserted literal in the golden's aarch64 block).
        let want = d2l(faithful_atan2(y, x, &asin, &cos_a64));
        let ph = format!("@@{idx}@@");
        // Locate the assertion containing this placeholder's row: the skeleton
        // rendered (already substituted on x86_64) keeps the aarch64 literal in
        // the block that holds the *filled* x86 value for this idx. Instead,
        // parse the rendered block by scanning around the known assertion line.
        // Robust approach: find the `atan2(Y, X)` call unique to this row and
        // read the `0x...` literal in the `#[cfg(target_arch = "aarch64")]`
        // arm right after it.
        let pos = rendered.find(needle).ok_or_else(|| {
            anyhow!("arch-selected row #{idx} ({needle}) not found in rendered golden")
        })?;
        let assert_start = rendered[..pos].rfind("assert_eq!").unwrap_or(pos);
        let block_start = rendered[assert_start..]
            .find("ARCH-SELECTED")
            .ok_or_else(|| anyhow!("row #{idx} ({needle}) is not an ARCH-SELECTED golden row"))?
            + assert_start;
        // Within the block, find the aarch64 arm's hex literal.
        let a64_seg = &rendered[block_start..];
        let a64_lit = extract_aarch64_literal(a64_seg).ok_or_else(|| {
            anyhow!("row #{idx} ({needle}) missing aarch64 literal in ARCH-SELECTED block")
        })?;
        anyhow::ensure!(
            a64_lit == want,
            "row #{idx} ({needle}): rendered aarch64 expected {a64_lit:#018x} but faithful atan2 \
             over the committed aarch64 COS_TAB yields {want:#018x}; aarch64 COS_TAB or golden \
             literal is stale (D14)"
        );
        // Also confirm the placeholder was actually filled (no residual marker).
        anyhow::ensure!(
            !rendered.matches(&ph).any(|_| true),
            "row #{idx}: placeholder {ph} left unfilled in golden"
        );
    }
    Ok(())
}

/// Extract the hex literal from an ARCH-SELECTED block's aarch64 arm
/// (`#[cfg(target_arch = "aarch64")] { 0x... }`).
fn extract_aarch64_literal(block: &str) -> Option<u64> {
    let marker = "#[cfg(target_arch = \"aarch64\")]";
    let start = block.find(marker)?;
    let arm = &block[start + marker.len()..];
    let brace = arm.find('{')?;
    let close = arm.find('}')?;
    let core = arm[brace + 1..close].trim();
    let hex = core.strip_prefix("0x")?;
    u64::from_str_radix(hex, 16).ok()
}

/// Pipe source through rustfmt (the repo toolchain) for canonical formatting.
fn rustfmt(repo_root: &Path, src: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .current_dir(repo_root)
        .spawn()
        .context("spawn rustfmt")?;
    use std::io::Write;
    child
        .stdin
        .as_mut()
        .ok_or_else(|| anyhow!("no stdin on rustfmt"))?
        .write_all(src.as_bytes())
        .context("write to rustfmt stdin")?;
    let out = child.wait_with_output().context("wait rustfmt")?;
    if !out.status.success() {
        bail!(
            "rustfmt failed: {}\n{}",
            out.status,
            String::from_utf8_lossy(&out.stderr)
        );
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn read_f64_table_rejects_excess_entries_without_panicking() {
        let dir = tempfile::tempdir().unwrap();
        let rows = (0..258)
            .map(|bits| format!("f64::from_bits(0x{bits:016x}),"))
            .collect::<Vec<_>>()
            .join("\n");
        fs::write(dir.path().join("table.rs"), rows).unwrap();

        let error = read_f64_table_257(dir.path(), "table.rs").unwrap_err();
        assert_eq!(
            error.to_string(),
            "table.rs: expected 257 entries, found more"
        );
    }
}
