//! `rivet-codegen mth-gen` — regenerate the Mth golden/sin-table files.
//!
//! The committed `crates/rivet-util/src/{mth_sin_table.rs, mth_atan_tables.rs,
//! mth_golden_tests.rs}` are `GENERATED — do not hand-edit` but had no checked-in
//! generator. This subcommand produces them from the *real* Paper Mth class:
//!
//! 1. unpacks the bundler jar classpath (shared with `extract`);
//! 2. compiles a small Java helper (`java/MthGen.java`, itself generated by
//!    `scripts/gen_mth_gen.py` from `data/mth_vectors.tsv`) against it;
//! 3. runs the helper and reads back:
//!      - the 65536-entry `SIN` table,
//!      - the 257-entry `ASIN_TAB` / `COS_TAB` tables,
//!      - the 1156 golden vectors (each Mth call recomputed via the real class);
//! 4. emits the three `.rs` files by substituting values into the committed
//!    structure (`data/mth_golden_skeleton.rs` for the golden file, the known
//!    table layout for the two table files), then pipes through `rustfmt`
//!    so the result matches the committed files byte-for-byte (they are
//!    rustfmt-idempotent, verified).
//!
//! Regeneration is idempotent: running it over the current committed files
//! reproduces them exactly (`git diff` stays clean).

use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, anyhow, bail};

use crate::extract;

/// Repo-relative paths of the generated files.
const GOLDEN_REL: &str = "crates/rivet-util/src/mth_golden_tests.rs";
const SIN_REL: &str = "crates/rivet-util/src/mth_sin_table.rs";
const ATAN_REL: &str = "crates/rivet-util/src/mth_atan_tables.rs";

pub fn run(bundler_flag: Option<&Path>, output_flag: Option<&Path>) -> Result<()> {
    let repo_root = extract::find_repo_root()?;
    let bundler = match bundler_flag {
        Some(p) => p.to_path_buf(),
        None => extract::default_bundler(&repo_root),
    };
    anyhow::ensure!(
        bundler.is_file(),
        "bundler jar not found at {} — pass --bundler or build Paper first",
        bundler.display()
    );

    let out_dir = match output_flag {
        Some(p) => p.to_path_buf(),
        None => repo_root.clone(),
    };
    fs::create_dir_all(&out_dir).with_context(|| format!("create {}", out_dir.display()))?;

    let (classpath, java, javac) = extract::prepare_runtime(&repo_root, &bundler)?;

    // Compile the Java oracle (generated by scripts/gen_mth_gen.py).
    let cache = repo_root.join("tools/rivet-codegen/.cache");
    let helper_dir = cache.join("mthhelper");
    fs::create_dir_all(&helper_dir)?;
    let helper_src = include_str!("java/MthGen.java");
    let helper_file = helper_dir.join("MthGen.java");
    fs::write(&helper_file, helper_src).context("write MthGen.java")?;
    extract::run_cmd(
        &javac,
        &[
            "-cp",
            &classpath,
            "-d",
            helper_dir.to_str().unwrap(),
            helper_file.to_str().unwrap(),
        ],
        "compile MthGen.java",
    )?;

    // Quiet log4j down so stdout only carries the oracle's table/vector lines.
    let log4j_off = cache.join("log4j2-off.xml");
    fs::write(
        &log4j_off,
        r#"<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="off"><Loggers><Root level="off"/></Loggers></Configuration>
"#,
    )
    .context("write log4j2-off.xml")?;

    let classpath_arg = format!("{classpath}:{}", helper_dir.display());
    let log4j_arg = format!("-Dlog4j.configurationFile={}", log4j_off.display());
    let out = extract::run_cmd_capture(
        &java,
        &[
            "-cp",
            &classpath_arg,
            "--enable-native-access=ALL-UNNAMED",
            &log4j_arg,
            "MthGen",
        ],
        "run MthGen",
    )?;

    let parsed = parse_oracle_output(&out)?;

    let golden_out = out_dir.join(GOLDEN_REL);
    if let Some(dir) = golden_out.parent() {
        fs::create_dir_all(dir).with_context(|| format!("create {}", dir.display()))?;
    }
    fs::write(
        &golden_out,
        render_golden(&repo_root, &parsed.vectors).context("render golden")?,
    )
    .with_context(|| format!("write {}", golden_out.display()))?;

    let sin_out = out_dir.join(SIN_REL);
    fs::write(&sin_out, render_sin(&parsed.sin))
        .with_context(|| format!("write {}", sin_out.display()))?;

    let atan_out = out_dir.join(ATAN_REL);
    fs::write(&atan_out, render_atan(&parsed.asin, &parsed.cos))
        .with_context(|| format!("write {}", atan_out.display()))?;

    println!(
        "Wrote {} ({} vectors), {} ({} entries), {} ({} + {} entries)",
        golden_out.display(),
        parsed.vectors.len(),
        sin_out.display(),
        parsed.sin.len(),
        atan_out.display(),
        parsed.asin.len(),
        parsed.cos.len()
    );
    Ok(())
}

struct OracleOutput {
    sin: Vec<String>,
    asin: Vec<String>,
    cos: Vec<String>,
    vectors: Vec<String>,
}

fn parse_oracle_output(out: &str) -> Result<OracleOutput> {
    let mut sin = Vec::new();
    let mut asin = Vec::new();
    let mut cos = Vec::new();
    let mut vectors = Vec::new();
    let mut section: Option<&str> = None;
    for line in out.lines() {
        match line {
            "SIN_TAB_START" => section = Some("sin"),
            "ASIN_TAB_START" => section = Some("asin"),
            "COS_TAB_START" => section = Some("cos"),
            "VECTORS_START" => section = Some("vec"),
            _ => match section {
                Some("sin") => sin.push(line.to_string()),
                Some("asin") => asin.push(line.to_string()),
                Some("cos") => cos.push(line.to_string()),
                Some("vec") => vectors.push(line.to_string()),
                _ => bail!("unexpected line before any section marker: {line:?}"),
            },
        }
    }
    anyhow::ensure!(
        sin.len() == 65536,
        "SIN table has {} entries, expected 65536",
        sin.len()
    );
    anyhow::ensure!(
        asin.len() == 257,
        "ASIN_TAB has {} entries, expected 257",
        asin.len()
    );
    anyhow::ensure!(
        cos.len() == 257,
        "COS_TAB has {} entries, expected 257",
        cos.len()
    );
    anyhow::ensure!(
        vectors.len() == 1156,
        "golden vectors: {} expected 1156",
        vectors.len()
    );
    Ok(OracleOutput {
        sin,
        asin,
        cos,
        vectors,
    })
}

/// Render mth_sin_table.rs — header + `f32::from_bits(...)` per entry.
fn render_sin(sin: &[String]) -> String {
    let mut s = String::new();
    s.push_str("#![allow(clippy::large_const_arrays)]\n");
    s.push_str("// GENERATED from net.minecraft.util.Mth (working/Paper) — do not hand-edit.\n");
    s.push_str("// Table: SIN[i] = (float)Math.sin(i / 10430.378350470453), i in [0,65536).\n");
    s.push_str("pub const SIN: [f32; 65536] = [\n");
    for v in sin {
        s.push_str("    f32::from_bits(");
        s.push_str(v);
        s.push_str("),\n");
    }
    s.push_str("];\n");
    s
}

/// Render mth_atan_tables.rs — ASIN_TAB then COS_TAB.
fn render_atan(asin: &[String], cos: &[String]) -> String {
    let mut s = String::new();
    s.push_str("// GENERATED from net.minecraft.util.Mth (working/Paper) — do not hand-edit.\n");
    s.push_str("// ASIN_TAB[ind] = Math.asin(ind/256.0); COS_TAB[ind] = Math.cos(Math.asin(ind/256.0)); ind in [0,257).\n");
    s.push_str("pub const ASIN_TAB: [f64; 257] = [\n");
    for v in asin {
        s.push_str("    f64::from_bits(");
        s.push_str(v);
        s.push_str("),\n");
    }
    s.push_str("];\n");
    s.push_str("pub const COS_TAB: [f64; 257] = [\n");
    for v in cos {
        s.push_str("    f64::from_bits(");
        s.push_str(v);
        s.push_str("),\n");
    }
    s.push_str("];\n");
    s
}

/// Substitute vector values into the committed golden skeleton, then rustfmt.
fn render_golden(repo_root: &Path, vectors: &[String]) -> Result<String> {
    let skeleton_path = repo_root.join("tools/rivet-codegen/data/mth_golden_skeleton.rs");
    let skeleton = fs::read_to_string(&skeleton_path)
        .with_context(|| format!("read skeleton {}", skeleton_path.display()))?;

    let mut filled = skeleton.clone();
    for (i, v) in vectors.iter().enumerate() {
        let ph = format!("@@{i}@@");
        let count = filled.matches(&ph).count();
        anyhow::ensure!(
            count == 1,
            "placeholder {ph} occurs {count} times in skeleton"
        );
        filled = filled.replace(&ph, v);
    }
    anyhow::ensure!(
        !filled.contains("@@"),
        "unfilled placeholders remain in golden output"
    );

    rustfmt(repo_root, &filled).with_context(|| "rustfmt golden tests")
}

/// Pipe source through rustfmt (the repo toolchain) for canonical formatting.
fn rustfmt(repo_root: &Path, src: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .current_dir(repo_root)
        .spawn()
        .context("spawn rustfmt")?;
    use std::io::Write;
    child
        .stdin
        .as_mut()
        .ok_or_else(|| anyhow!("no stdin on rustfmt"))?
        .write_all(src.as_bytes())
        .context("write to rustfmt stdin")?;
    let out = child.wait_with_output().context("wait rustfmt")?;
    if !out.status.success() {
        bail!(
            "rustfmt failed: {}\n{}",
            out.status,
            String::from_utf8_lossy(&out.stderr)
        );
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}
