// `Mth.PI`/`HALF_PI`/`TWO_PI`/`DEG_TO_RAD`/`RAD_TO_DEG`/`SQRT_OF_TWO` are the
// exact f32 truncations of the Java `(float)` casts (clippy's
// `approx_constant` would suggest bit-identical `f32::consts` values; the
// literals are kept to mirror the Java source).
#![allow(clippy::approx_constant)]

//! Port of `net.minecraft.util.Mth` (working/Paper,
//! `paper-server/src/minecraft/java/net/minecraft/util/Mth.java`).
//!
//! PARITY-CRITICAL. The 65536-entry `SIN` table, the 257-entry `ASIN_TAB`/
//! `COS_TAB` tables, and `FRAC_BIAS` are generated by Java (`Math.sin`/
//! `Math.asin`/`Math.cos`, bit-exact `doubleToRawLongBits`) in
//! `mth_sin_table.rs` / `mth_atan_tables.rs` — they are NEVER computed at
//! runtime (PORTING.md: "Never substitute `f32::sin`"). Golden tests in
//! `mth_golden_tests.rs` pin bit-exact outputs against the same Java
//! expressions.
//!
//! Type-shape notes (PORTING.md):
//! - All `int`/`long` arithmetic wraps (`wrapping_*`), matching Java's
//!   two's-complement overflow.
//! - Java `>>>` is a logical shift on the `u32`/`u64` view.
//! - Java `(int)Math.floor(d)` / `(int)Math.ceil(d)` saturate and map NaN->0;
//!   Rust `as` matches.
//! - Cross-unit types are declared in `mth_stubs.rs` (see the `RivetTodo(#206)`
//!   marker there): `RandomSource` is owned by mc.util.random, `Vec3`/`AABB` by
//!   mc.world.phys, `Vec3f`/`Quaternionf` by JOML, `ARGB` by mc.util,
//!   `Fraction` by commons-lang3. The LCG stub `SingleThreadedRandomSource` is
//!   minimal but bit-exact (48-bit LCG + Marsaglia polar gaussian).

use crate::mth_atan_tables::{ASIN_TAB, COS_TAB};
use crate::mth_sin_table::SIN;
use crate::mth_stubs::{Aabb, Fraction, Quaternionf, Vec3, Vec3f};
use crate::random_source::{RandomSource, random_source_create_thread_local_instance_with_seed};

/// `Mth.PI` = `(float)Math.PI`.
pub const PI: f32 = 3.1415927;
/// `Mth.HALF_PI` = `(float)(Math.PI / 2)`.
pub const HALF_PI: f32 = 1.5707964;
/// `Mth.TWO_PI` = `(float)(Math.PI * 2)`.
pub const TWO_PI: f32 = 6.2831855;
/// `Mth.DEG_TO_RAD` = `(float)(Math.PI / 180.0)`.
pub const DEG_TO_RAD: f32 = 0.017453292;
/// `Mth.RAD_TO_DEG` = `180.0F / (float)Math.PI`.
pub const RAD_TO_DEG: f32 = 57.295776;
/// `Mth.EPSILON`.
pub const EPSILON: f32 = 1.0E-5;
/// `Mth.SQRT_OF_TWO` = `sqrt(2.0F)`.
pub const SQRT_OF_TWO: f32 = 1.4142135;
/// `Mth.X_AXIS` = `new Vector3f(1.0F, 0.0F, 0.0F)` (JOML `Vector3fc`).
pub const X_AXIS: Vec3f = Vec3f {
    x: 1.0,
    y: 0.0,
    z: 0.0,
};
/// `Mth.Y_AXIS` = `new Vector3f(0.0F, 1.0F, 0.0F)`.
pub const Y_AXIS: Vec3f = Vec3f {
    x: 0.0,
    y: 1.0,
    z: 0.0,
};
/// `Mth.Z_AXIS` = `new Vector3f(0.0F, 0.0F, 1.0F)`.
pub const Z_AXIS: Vec3f = Vec3f {
    x: 0.0,
    y: 0.0,
    z: 1.0,
};

// `Mth.SIN_QUANTIZATION` (65536), `Mth.SIN_MASK` (65535),
// `Mth.COS_OFFSET` (16384), `Mth.SIN_SCALE` (10430.378350470453) are
// expressed inline below exactly as in the Java.

/// `Mth.sin(double i)` — table lookup, never a libm call.
pub fn sin(i: f64) -> f32 {
    SIN[(i * 10430.378350470453) as i64 as usize & 65535]
}

/// `Mth.cos(double i)`.
pub fn cos(i: f64) -> f32 {
    SIN[((i * 10430.378350470453 + 16384.0) as i64) as usize & 65535]
}

/// `Mth.sqrt(float x)`.
pub fn sqrt(x: f32) -> f32 {
    x.sqrt()
}

/// `Mth.floor(float v)` = `(int)Math.floor(v)`.
pub fn floor(v: f32) -> i32 {
    v.floor() as i32
}

/// `Mth.floor(double v)`.
pub fn floor_d(v: f64) -> i32 {
    v.floor() as i32
}

/// `Mth.lfloor(double v)` = `(long)Math.floor(v)`.
pub fn lfloor(v: f64) -> i64 {
    v.floor() as i64
}

/// `Mth.abs(float v)`.
pub fn abs(v: f32) -> f32 {
    v.abs()
}

/// `Mth.abs(int v)`.
///
/// Java `Math.abs(int)` wraps for `Integer.MIN_VALUE` (`Math.abs` returns the
/// negated value, which overflows back to `MIN_VALUE`).
pub fn abs_i32(v: i32) -> i32 {
    v.wrapping_abs()
}

/// `Mth.ceil(float v)` = `(int)Math.ceil(v)`.
pub fn ceil(v: f32) -> i32 {
    v.ceil() as i32
}

/// `Mth.ceil(double v)`.
pub fn ceil_d(v: f64) -> i32 {
    v.ceil() as i32
}

/// `Mth.ceilLong(double v)` = `(long)Math.ceil(v)`.
pub fn ceil_long(v: f64) -> i64 {
    v.ceil() as i64
}

/// `Mth.clamp(int value, int min, int max)` — `Math.min(Math.max(value, min),
/// max)`. The Java `int` and `long` overloads have identical bodies, so a
/// single generic over `Ord` is faithful to both (the golden tests call this
/// with both `i32` and `i64`).
pub fn clamp<T: Ord>(value: T, min: T, max: T) -> T {
    min.max(value).min(max)
}

/// `Mth.clamp(float value, float min, float max)`.
///
/// Java: `value < min ? min : Math.min(value, max)` — a NaN `value` passes the
/// `<` test (false) and `Math.min(value, max)` propagates a NaN from *either*
/// operand (Java `Math.min` returns NaN if either is NaN; Rust `f32::min`
/// returns the non-NaN operand instead, so NaN is handled explicitly for both
/// operands).
pub fn clamp_f32(value: f32, min: f32, max: f32) -> f32 {
    if value < min {
        min
    } else if value.is_nan() {
        value
    } else if max.is_nan() {
        max
    } else {
        value.min(max)
    }
}

/// `Mth.clamp(double value, double min, double max)` — same NaN semantics as
/// `clamp_f32`.
pub fn clamp_f64(value: f64, min: f64, max: f64) -> f64 {
    if value < min {
        min
    } else if value.is_nan() {
        value
    } else if max.is_nan() {
        max
    } else {
        value.min(max)
    }
}

/// `Mth.clampedLerp(double factor, double min, double max)`.
pub fn clamped_lerp(factor: f64, min: f64, max: f64) -> f64 {
    if factor < 0.0 {
        min
    } else if factor > 1.0 {
        max
    } else {
        lerp(factor, min, max)
    }
}

/// `Mth.clampedLerp(float factor, float min, float max)`.
pub fn clamped_lerp_f32(factor: f32, min: f32, max: f32) -> f32 {
    if factor < 0.0 {
        min
    } else if factor > 1.0 {
        max
    } else {
        lerp_f32(factor, min, max)
    }
}

/// `Mth.absMax(int a, int b)` — `Math.abs` wraps for `Integer.MIN_VALUE`.
pub fn abs_max(a: i32, b: i32) -> i32 {
    a.wrapping_abs().max(b.wrapping_abs())
}

/// `Mth.absMax(float a, float b)` = `Math.max(Math.abs(a), Math.abs(b))`.
///
/// Java `Math.max` propagates NaN from *either* operand, whereas Rust `f32::max` returns
/// the non-NaN operand when the other is NaN, so NaN is handled explicitly. Absing first
/// matches Java's `Math.abs`: `-0.0` becomes `+0.0`, and a NaN has its sign bit cleared
/// while its payload is preserved, so signed-zero results are `+0.0` and propagated NaN
/// is the sign-cleared input NaN.
pub fn abs_max_f32(a: f32, b: f32) -> f32 {
    let a = a.abs();
    let b = b.abs();
    if a.is_nan() {
        a
    } else if b.is_nan() {
        b
    } else {
        a.max(b)
    }
}

/// `Mth.absMax(double a, double b)` — same NaN/signed-zero semantics as `abs_max_f32`.
pub fn abs_max_f64(a: f64, b: f64) -> f64 {
    let a = a.abs();
    let b = b.abs();
    if a.is_nan() {
        a
    } else if b.is_nan() {
        b
    } else {
        a.max(b)
    }
}

/// `Mth.chessboardDistance(int x0, int z0, int x1, int z1)` — Java int
/// subtraction wraps.
pub fn chessboard_distance(x0: i32, z0: i32, x1: i32, z1: i32) -> i32 {
    abs_max(x1.wrapping_sub(x0), z1.wrapping_sub(z0))
}

/// `Mth.floorDiv(int a, int b)` = `Math.floorDiv(a, b)`.
///
/// JDK semantics (result rounds toward negative infinity, i.e. has the sign of
/// the divisor): `q = a / b; r = a % b; (r != 0 && ((r ^ b) < 0)) ? q - 1 : q`
/// — with wrapping int arithmetic. (Rust `div_euclid` gives a non-negative
/// remainder and a *different* quotient for negative divisors.)
pub fn floor_div(a: i32, b: i32) -> i32 {
    let q = a.wrapping_div(b);
    let r = a.wrapping_rem(b);
    if r != 0 && (r ^ b) < 0 {
        q.wrapping_sub(1)
    } else {
        q
    }
}

/// `Mth.floorDiv(long a, long b)` = `Math.floorDiv` — the `long` overload
/// (identical JDK body, wrapping arithmetic).
pub fn floor_div_i64(a: i64, b: i64) -> i64 {
    let q = a.wrapping_div(b);
    let r = a.wrapping_rem(b);
    if r != 0 && (r ^ b) < 0 {
        q.wrapping_sub(1)
    } else {
        q
    }
}

/// `Mth.nextInt(RandomSource random, int minInclusive, int maxInclusive)` —
/// Java int arithmetic wraps.
pub fn next_int<R: RandomSource>(random: &mut R, min_inclusive: i32, max_inclusive: i32) -> i32 {
    if min_inclusive >= max_inclusive {
        min_inclusive
    } else {
        random
            .next_int_bound(max_inclusive.wrapping_sub(min_inclusive).wrapping_add(1))
            .wrapping_add(min_inclusive)
    }
}

/// `Mth.nextFloat(RandomSource random, float min, float max)`.
pub fn next_float<R: RandomSource>(random: &mut R, min: f32, max: f32) -> f32 {
    if min >= max {
        min
    } else {
        random.next_float() * (max - min) + min
    }
}

/// `Mth.nextDouble(RandomSource random, double min, double max)`.
pub fn next_double<R: RandomSource>(random: &mut R, min: f64, max: f64) -> f64 {
    if min >= max {
        min
    } else {
        random.next_double() * (max - min) + min
    }
}

/// `Mth.equal(float a, float b)`.
pub fn equal(a: f32, b: f32) -> bool {
    (b - a).abs() < 1.0e-5
}

/// `Mth.equal(double a, double b)`.
///
/// Java compares against the float literal `1.0E-5F` widened to double
/// (`9.9999997473787516e-6`), not the exact f64 `1e-5` — the threshold is
/// written as the f32 constant and cast so the widening is bit-exact.
pub fn equal_d(a: f64, b: f64) -> bool {
    (b - a).abs() < (1.0e-5f32) as f64
}

/// `Mth.positiveModulo(int input, int mod)` = `Math.floorMod(input, mod)`.
///
/// `Math.floorMod` has the *sign of the divisor* (unlike Rust `rem_euclid`,
/// which is always non-negative). Faithful port of the JDK:
/// `r = input % mod; r == 0 ? 0 : (r ^ mod) < 0 ? r + mod : r` with wrapping
/// int arithmetic.
pub fn positive_modulo(input: i32, m: i32) -> i32 {
    let r = input.wrapping_rem(m);
    if r == 0 {
        0
    } else if (r ^ m) < 0 {
        r.wrapping_add(m)
    } else {
        r
    }
}

/// `Mth.positiveModulo(float input, float mod)`.
pub fn positive_modulo_f32(input: f32, m: f32) -> f32 {
    (input % m + m) % m
}

/// `Mth.positiveModulo(double input, double mod)`.
pub fn positive_modulo_f64(input: f64, m: f64) -> f64 {
    (input % m + m) % m
}

/// `Mth.isMultipleOf(int dividend, int divisor)`.
pub fn is_multiple_of(dividend: i32, divisor: i32) -> bool {
    dividend % divisor == 0
}

/// `Mth.packDegrees(float angle)` = `(byte)floor(angle * 256.0F / 360.0F)`.
pub fn pack_degrees(angle: f32) -> i8 {
    floor(angle * 256.0 / 360.0) as i8
}

/// `Mth.unpackDegrees(byte rot)` = `rot * 360 / 256.0F` (`byte` sign-extends
/// to `int` before the f32 arithmetic).
pub fn unpack_degrees(rot: i8) -> f32 {
    (rot as i32) as f32 * 360.0 / 256.0
}

/// `Mth.wrapDegrees(int angle)`.
pub fn wrap_degrees(angle: i32) -> i32 {
    let mut normalized = angle % 360;
    if normalized >= 180 {
        normalized -= 360;
    }
    if normalized < -180 {
        normalized += 360;
    }
    normalized
}

/// `Mth.wrapDegrees(long angle)`.
pub fn wrap_degrees_i64(angle: i64) -> f32 {
    let mut normalized = (angle % 360) as f32;
    if normalized >= 180.0 {
        normalized -= 360.0;
    }
    if normalized < -180.0 {
        normalized += 360.0;
    }
    normalized
}

/// `Mth.wrapDegrees(float angle)`.
pub fn wrap_degrees_f32(angle: f32) -> f32 {
    let mut normalized = angle % 360.0;
    if normalized >= 180.0 {
        normalized -= 360.0;
    }
    if normalized < -180.0 {
        normalized += 360.0;
    }
    normalized
}

/// `Mth.wrapDegrees(double angle)`.
pub fn wrap_degrees_f64(angle: f64) -> f64 {
    let mut normalized = angle % 360.0;
    if normalized >= 180.0 {
        normalized -= 360.0;
    }
    if normalized < -180.0 {
        normalized += 360.0;
    }
    normalized
}

/// `Mth.wrapDegrees90(float angle)`.
pub fn wrap_degrees90(angle: f32) -> f32 {
    let mut normalized = angle % 90.0;
    if normalized >= 45.0 {
        normalized -= 90.0;
    }
    if normalized < -45.0 {
        normalized += 90.0;
    }
    normalized
}

/// `Mth.degreesDifference(float fromAngle, float toAngle)`.
pub fn degrees_difference(from: f32, to: f32) -> f32 {
    wrap_degrees_f32(to - from)
}

/// `Mth.degreesDifferenceAbs(float angleA, float angleB)`.
pub fn degrees_difference_abs(a: f32, b: f32) -> f32 {
    abs(degrees_difference(a, b))
}

/// `Mth.rotateIfNecessary(float baseAngle, float targetAngle, float maxAngleDiff)`.
pub fn rotate_if_necessary(base: f32, target: f32, max_angle_diff: f32) -> f32 {
    let delta = degrees_difference(base, target);
    let delta_clamped = clamp_f32(delta, -max_angle_diff, max_angle_diff);
    target - delta_clamped
}

/// `Mth.approach(float current, float target, float increment)`.
pub fn approach(current: f32, target: f32, increment: f32) -> f32 {
    let increment = abs(increment);
    if current < target {
        clamp_f32(current + increment, current, target)
    } else {
        clamp_f32(current - increment, target, current)
    }
}

/// `Mth.approachDegrees(float current, float target, float increment)`.
pub fn approach_degrees(current: f32, target: f32, increment: f32) -> f32 {
    let difference = degrees_difference(current, target);
    approach(current, current + difference, increment)
}

/// `Mth.getInt(String input, int def)` — `NumberUtils.toInt`.
///
/// Apache Commons NumberUtils.toInt semantics: whitespace is not trimmed,
/// optional leading sign, base-10 digits only, overflow -> `def`.
pub fn get_int(input: Option<&str>, def: i32) -> i32 {
    match input {
        None => def,
        Some(s) => parse_java_int(s).unwrap_or(def),
    }
}

fn parse_java_int(s: &str) -> Option<i32> {
    let b = s.as_bytes();
    if b.is_empty() {
        return None;
    }
    let (neg, idx) = match b[0] {
        b'+' => (false, 1),
        b'-' => (true, 1),
        _ => (false, 0),
    };
    if idx >= b.len() {
        return None;
    }
    let mut acc: i64 = 0;
    for &c in &b[idx..] {
        if !c.is_ascii_digit() {
            return None;
        }
        let digit = (c - b'0') as i64;
        // Java `Integer.parseInt` throws `NumberFormatException` on any
        // overflow (`NumberUtils.toInt` maps it to `def`), so bail before the
        // i64 accumulator itself would wrap (a wrapped accumulator could land
        // back inside the i32 range and yield a wrong value).
        if acc > (i64::MAX - digit) / 10 {
            return None;
        }
        acc = acc * 10 + digit;
    }
    let signed = if neg { -acc } else { acc };
    if signed < i32::MIN as i64 || signed > i32::MAX as i64 {
        return None;
    }
    Some(signed as i32)
}

/// `Mth.smallestEncompassingPowerOfTwo(int input)` — Java int arithmetic
/// wraps. The `|`/`>>` chain cannot overflow on any input (bitwise OR of a
/// value with its right-shifts stays within i32), so only the final
/// `result + 1` needs wrapping: it overflows to `Integer.MIN_VALUE` for
/// `input` near `MAX_VALUE`.
pub fn smallest_encompassing_power_of_two(input: i32) -> i32 {
    let mut result = input.wrapping_sub(1);
    result |= result >> 1;
    result |= result >> 2;
    result |= result >> 4;
    result |= result >> 8;
    result |= result >> 16;
    result.wrapping_add(1)
}

/// `Mth.smallestSquareSide(int itemCount)`.
///
/// Java throws `IllegalArgumentException` in all build configurations; the
/// check is written as an explicit `panic!` (not `assert!`) so the negative
/// path aborts identically in debug and release builds.
pub fn smallest_square_side(item_count: i32) -> i32 {
    if item_count < 0 {
        panic!("itemCount must be greater than or equal to zero");
    }
    ceil_d((item_count as f64).sqrt())
}

/// `Mth.isPowerOfTwo(int input)` — `input - 1` wraps (Java int arithmetic).
pub fn is_power_of_two(input: i32) -> bool {
    input != 0 && (input & input.wrapping_sub(1)) == 0
}

/// `Mth.isPowerOfTwo(long input)` — `input - 1` wraps.
pub fn is_power_of_two_i64(input: i64) -> bool {
    input != 0 && (input & input.wrapping_sub(1)) == 0
}

/// `Mth.ceillog2(int input)`.
pub fn ceillog2(mut input: i32) -> i32 {
    if !is_power_of_two(input) {
        input = smallest_encompassing_power_of_two(input);
    }
    MULTIPLY_DE_BRUIJN_BIT_POSITION[((input as i64 * 125613361) >> 27) as usize & 31]
}

const MULTIPLY_DE_BRUIJN_BIT_POSITION: [i32; 32] = [
    0, 1, 28, 2, 29, 14, 24, 3, 30, 22, 20, 15, 25, 17, 4, 8, 31, 27, 13, 23, 21, 19, 16, 7, 26,
    12, 18, 6, 11, 5, 10, 9,
];

/// `Mth.log2(int input)`.
pub fn log2(input: i32) -> i32 {
    ceillog2(input) - if is_power_of_two(input) { 0 } else { 1 }
}

/// `Mth.frac(float num)`.
pub fn frac(num: f32) -> f32 {
    num - floor(num) as f32
}

/// `Mth.frac(double num)`.
pub fn frac_f64(num: f64) -> f64 {
    num - lfloor(num) as f64
}

/// `Mth.getSeed(int x, int y, int z)` (deprecated in Java, kept for parity).
///
/// See `java_hash::get_seed` for the arithmetic details.
pub fn get_seed(x: i32, y: i32, z: i32) -> i64 {
    crate::java_hash::get_seed(x, y, z)
}

/// `Mth.createInsecureUUID(RandomSource random)`.
pub fn create_insecure_uuid<R: RandomSource>(random: &mut R) -> Uuid {
    let most = random.next_long() & -61441 | 16384;
    let least = random.next_long() & 4611686018427387903 | i64::MIN;
    Uuid { most, least }
}

/// Minimal UUID value type — the `java.util.UUID` string surface only (the
/// `most`/`least` bit layout Java's `UUID` exposes). Added by the status
/// protocol port for `NameAndId` (`UUIDUtil.STRING_CODEC`). No version/variant
/// validation: Java's `UUID(long, long)` constructor accepts any bit pattern.
///
/// `Hash` is derived so `GameProfile` (authlib, #198) can derive `Hash` over
/// its record components; Java's `UUID.hashCode()` is `(int)(msb ^ (msb >>> 32))
/// ^ (int)(lsb ^ (lsb >>> 32))`, and deriving over the two `i64` fields gives
/// the required `a == b ⇒ hash(a) == hash(b)` contract with a different spread
/// (hash values are not wire/equality-visible, only the consistency contract is).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Uuid {
    pub most: i64,
    pub least: i64,
}

impl Uuid {
    /// `UUID.fromString(String)` — Java's parser, exactly (JDK 25). Accepts
    /// any string of at most 36 chars with exactly 4 dashes whose groups parse
    /// as signed base-16 longs, masking each group to its 32/16/16/16/48-bit
    /// width (short groups pad with zeros, so `1-2-3-4-5` is valid; a group
    /// wider than its field truncates, so `100000000-2-3-4-5` is valid).
    /// Braces, the `urn:uuid:` prefix, the undashed 32-char form, and a group
    /// whose value exceeds `Long.MAX_VALUE` (e.g. `8000000000000000`) are
    /// REJECTED — `UUID.fromString` never accepted them (verified against the
    /// JDK 25 JVM Paper's oracle runs on). No value validation: Java's
    /// `UUID(long, long)` constructor accepts any bit pattern (the all-zero
    /// UUID parses fine).
    ///
    /// `Err` carries Java's exact exception message (`e.getMessage()` from the
    /// `IllegalArgumentException`/`NumberFormatException` `UUID.fromString`
    /// throws), so `UUIDUtil.STRING_CODEC` can reproduce its
    /// `"Invalid UUID <s>: <cause>"` error verbatim.
    pub fn from_string(name: &str) -> Result<Uuid, String> {
        let len = name.len();
        // Java's `UUID.fromString` rejects strings longer than 36 chars
        // outright ("UUID string too large").
        if len > 36 {
            return Err("UUID string too large".to_string());
        }
        // Locate the dashes exactly as repeated `indexOf('-', ...)` would; a
        // 5th dash (or fewer than 4) is "Invalid UUID string".
        let dash_after = |start: usize| name[start..].find('-').map(|i| start + i);
        let d1 = dash_after(0);
        let d2 = d1.and_then(|d| dash_after(d + 1));
        let d3 = d2.and_then(|d| dash_after(d + 1));
        let d4 = d3.and_then(|d| dash_after(d + 1));
        let d5 = d4.and_then(|d| dash_after(d + 1));
        let (d1, d2, d3, d4) = match (d1, d2, d3, d4, d5) {
            (Some(a), Some(b), Some(c), Some(d), None) => (a, b, c, d),
            _ => return Err(format!("Invalid UUID string: {name}")),
        };
        // `Long.parseLong(segment, 16)` masked to the field width. Each group
        // parses as a SIGNED long (values beyond `Long.MAX_VALUE` overflow),
        // then masks — exactly Java's `parseLong(...) & 0x...`.
        let g1 = (parse_long_hex(&name[..d1])? as u64) & 0xffff_ffff;
        let g2 = (parse_long_hex(&name[d1 + 1..d2])? as u64) & 0xffff;
        let g3 = (parse_long_hex(&name[d2 + 1..d3])? as u64) & 0xffff;
        let g4 = (parse_long_hex(&name[d3 + 1..d4])? as u64) & 0xffff;
        let g5 = (parse_long_hex(&name[d4 + 1..len])? as u64) & 0xffff_ffff_ffff;
        Ok(Uuid {
            most: ((g1 << 32) | (g2 << 16) | g3) as i64,
            least: ((g4 << 48) | g5) as i64,
        })
    }
}

/// `Long.parseLong(String, 16)` — Java's signed-base-16 parser, with the exact
/// JDK-25 accept/reject set and `NumberFormatException` messages. Parses a
/// segment into a signed `i64` (a value outside `[i64::MIN, i64::MAX]` — e.g. a
/// 16-hex-digit group starting `8..f` — is rejected), accumulating negatively
/// the way Java does so `Long.MIN_VALUE` parses. `Err` is Java's message:
/// `For input string: "" under radix 16` for an empty segment, `Error at index
/// N in: "..."` for a non-hex digit or overflow, and the lone-sign cases.
fn parse_long_hex(segment: &str) -> Result<i64, String> {
    let bytes = segment.as_bytes();
    if bytes.is_empty() {
        // Java `NumberFormatException.forInputString("", 16)`.
        return Err("For input string: \"\" under radix 16".to_string());
    }
    let first = bytes[0];
    let signed = first == b'-' || first == b'+';
    let negative = first == b'-';
    // Java's `digit` sentinel `~0xFF` when the first char is a sign. `i` is 1
    // after the first char was consumed by `s.charAt(i++)`.
    let mut digit: i64 = if signed { -256 } else { hex_digit_value(first) };
    let mut i = 1;
    if digit >= 0 || (digit == -256 && bytes.len() > 1) {
        // `limit`: `MIN_VALUE` for a leading '-', else `MIN_VALUE + 1`.
        let limit = if negative { i64::MIN } else { i64::MIN + 1 };
        let multmin = limit / 16;
        // `result = -(digit & 0xFF)`: for a sign, `digit & 0xFF` is 0, so
        // `result` starts at 0; for a hex digit `d`, it starts at `-d`.
        let mut result = -(digit & 0xff);
        let mut in_range = true;
        loop {
            if i >= bytes.len() {
                break;
            }
            digit = hex_digit_value(bytes[i]);
            i += 1;
            if digit < 0 {
                // Non-hex digit: Java's `digit >= 0` loop condition fails;
                // `inRange` keeps its previous (true) value.
                break;
            }
            // `inRange = result > multmin || result == multmin && digit <= (int)(radix*multmin - limit)`.
            let cast = (16 * multmin - limit) as i32 as i64;
            in_range = result > multmin || (result == multmin && digit <= cast);
            if !in_range {
                break;
            }
            result = 16 * result - digit;
        }
        if in_range && i == bytes.len() && digit >= 0 {
            return Ok(if negative { result } else { -result });
        }
    }
    // `NumberFormatException.forCharSequence(s, 0, len, i - (digit < -1 ? 0 : 1))`.
    let error_index = i - if digit < -1 { 0 } else { 1 };
    Err(format!("Error at index {error_index} in: \"{segment}\""))
}

/// `Character.digit(char, 16)` for ASCII hex digits; `-1` for anything else.
fn hex_digit_value(c: u8) -> i64 {
    match c {
        b'0'..=b'9' => (c - b'0') as i64,
        b'a'..=b'f' => (c - b'a' + 10) as i64,
        b'A'..=b'F' => (c - b'A' + 10) as i64,
        _ => -1,
    }
}

/// `UUID.toString()` — the canonical `8-4-4-4-12` lowercase-hex form.
impl std::fmt::Display for Uuid {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let most = format!("{:016x}", self.most as u64);
        let least = format!("{:016x}", self.least as u64);
        write!(
            f,
            "{}-{}-{}-{}-{}",
            &most[0..8],
            &most[8..12],
            &most[12..16],
            &least[0..4],
            &least[4..16]
        )
    }
}

/// `Mth.inverseLerp(double value, double min, double max)`.
pub fn inverse_lerp(value: f64, min: f64, max: f64) -> f64 {
    (value - min) / (max - min)
}

/// `Mth.inverseLerp(float value, float min, float max)`.
pub fn inverse_lerp_f32(value: f32, min: f32, max: f32) -> f32 {
    (value - min) / (max - min)
}

/// `Mth.atan2(double y, double x)` — the table-based implementation from
/// `Mth.java` (fast inverse sqrt + 257-entry asin/cos LUT). Never `f64::atan2`.
pub fn atan2(y: f64, x: f64) -> f64 {
    let mut y = y;
    let mut x = x;
    let d2 = x * x + y * y;
    if d2.is_nan() {
        return f64::NAN;
    }
    let neg_y = y < 0.0;
    if neg_y {
        y = -y;
    }
    let neg_x = x < 0.0;
    if neg_x {
        x = -x;
    }
    let steep = y > x;
    if steep {
        // Java's `t = x; x = y; y = t` kept verbatim (see `atan2` doc).
        #[allow(clippy::manual_swap)]
        {
            let t = x;
            x = y;
            y = t;
        }
    }
    let rinv = fast_inv_sqrt(d2);
    x *= rinv;
    y *= rinv;
    let yp = FRAC_BIAS + y;
    // Java `(int)Double.doubleToRawLongBits(yp)` truncates the long to int;
    // `longBitsToDouble`/`as` on the sign+exponent+high-mantissa bits keeps
    // index in [0, 256] for the 257-entry LUT.
    let index = ((yp.to_bits() as i64) as i32) as usize;
    let phi = ASIN_TAB[index];
    let c_phi = COS_TAB[index];
    let s_phi = yp - FRAC_BIAS;
    let sd = y * c_phi - x * s_phi;
    let d = (6.0 + sd * sd) * sd * 0.16666666666666666;
    let mut theta = phi + d;
    if steep {
        theta = std::f64::consts::FRAC_PI_2 - theta;
    }
    if neg_x {
        theta = std::f64::consts::PI - theta;
    }
    if neg_y {
        theta = -theta;
    }
    theta
}

/// `Mth.FRAC_BIAS` — `Double.longBitsToDouble(4805340802404319232L)`.
const FRAC_BIAS: f64 = f64::from_bits(0x42b0000000000000);

/// `Mth.invSqrt(float x)` — `org.joml.Math.invsqrt(x)` =
/// `1.0f / (float)Math.sqrt(x)`.
pub fn inv_sqrt(x: f32) -> f32 {
    x.sqrt().recip()
}

/// `Mth.invSqrt(double x)` — `org.joml.Math.invsqrt(x)` =
/// `1.0 / Math.sqrt(x)`.
pub fn inv_sqrt_f64(x: f64) -> f64 {
    x.sqrt().recip()
}

/// `Mth.fastInvSqrt(double x)`.
///
/// Java `6910469410427058090L - (i >> 1)` wraps silently (two's-complement);
/// the wrapping subtraction is preserved so e.g. `x = -0.0` (whose wrapped
/// `i` overflows i64) produces the same bits in debug and release.
pub fn fast_inv_sqrt(mut x: f64) -> f64 {
    let xhalf = 0.5 * x;
    let mut i = x.to_bits() as i64;
    i = 6910469410427058090i64.wrapping_sub(i >> 1);
    x = f64::from_bits(i as u64);
    x * (1.5 - xhalf * x * x)
}

/// `Mth.fastInvCubeRoot(float x)`.
pub fn fast_inv_cube_root(x: f32) -> f32 {
    let mut i = x.to_bits() as i32;
    i = 1419967116 - i / 3;
    let mut y = f32::from_bits(i as u32);
    y = 0.6666667 * y + 1.0 / (3.0 * y * y * x);
    0.6666667 * y + 1.0 / (3.0 * y * y * x)
}

/// `Mth.hsvToRgb(float hue, float saturation, float value)`.
pub fn hsv_to_rgb(hue: f32, saturation: f32, value: f32) -> i32 {
    hsv_to_argb(hue, saturation, value, 0)
}

/// `Mth.hsvToArgb(float hue, float saturation, float value, int alpha)`.
pub fn hsv_to_argb(hue: f32, saturation: f32, value: f32, alpha: i32) -> i32 {
    let h = (hue * 6.0) as i32 % 6;
    let f = hue * 6.0 - h as f32;
    let p = value * (1.0 - saturation);
    let q = value * (1.0 - f * saturation);
    let t = value * (1.0 - (1.0 - f) * saturation);
    let (red, green, blue) = match h {
        0 => (value, t, p),
        1 => (q, value, p),
        2 => (p, value, t),
        3 => (p, q, value),
        4 => (t, p, value),
        5 => (value, p, q),
        _ => panic!(
            "Something went wrong when converting from HSV to RGB. Input was {}, {}, {}",
            hue, saturation, value
        ),
    };
    argb_color(
        alpha,
        clamp((red * 255.0) as i32, 0, 255),
        clamp((green * 255.0) as i32, 0, 255),
        clamp((blue * 255.0) as i32, 0, 255),
    )
}

/// RivetTodo(#206): `ARGB.color(int alpha, int red, int green, int blue)` —
/// only this one entry point of `net.minecraft.util.ARGB` is ported.
pub fn argb_color(alpha: i32, red: i32, green: i32, blue: i32) -> i32 {
    (alpha & 0xFF) << 24 | (red & 0xFF) << 16 | (green & 0xFF) << 8 | blue & 0xFF
}

/// `Mth.murmurHash3Mixer(int hash)`.
pub fn murmur_hash3_mixer(hash: i32) -> i32 {
    crate::java_hash::murmur_hash3_mixer(hash)
}

/// `Mth.binarySearch(int from, int to, IntPredicate condition)`.
///
/// The `condition` is a *predicate* (first true => answer in `[from, middle]`).
pub fn binary_search<F: Fn(i32) -> bool>(mut from: i32, to: i32, condition: F) -> i32 {
    let mut len = to - from;
    while len > 0 {
        let half = len / 2;
        let middle = from + half;
        if condition(middle) {
            len = half;
        } else {
            from = middle + 1;
            len -= half + 1;
        }
    }
    from
}

/// `Mth.lerpInt(float alpha1, int p0, int p1)` — Java int arithmetic wraps.
pub fn lerp_int(alpha1: f32, p0: i32, p1: i32) -> i32 {
    p0.wrapping_add(floor(alpha1 * (p1.wrapping_sub(p0)) as f32))
}

/// `Mth.lerpDiscrete(float alpha1, int p0, int p1)` — Java int arithmetic wraps.
pub fn lerp_discrete(alpha1: f32, p0: i32, p1: i32) -> i32 {
    let delta = p1.wrapping_sub(p0);
    p0.wrapping_add(floor(alpha1 * (delta.wrapping_sub(1)) as f32))
        .wrapping_add(if alpha1 > 0.0 { 1 } else { 0 })
}

/// `Mth.lerp(float alpha1, float p0, float p1)`.
pub fn lerp_f32(alpha1: f32, p0: f32, p1: f32) -> f32 {
    p0 + alpha1 * (p1 - p0)
}

/// `Mth.lerp(double alpha1, double p0, double p1)`.
pub fn lerp(alpha1: f64, p0: f64, p1: f64) -> f64 {
    p0 + alpha1 * (p1 - p0)
}

/// `Mth.lerp(double, Vec3, Vec3)`.
pub fn lerp_vec3(alpha: f64, p1: Vec3, p2: Vec3) -> Vec3 {
    Vec3::new(
        lerp(alpha, p1.x, p2.x),
        lerp(alpha, p1.y, p2.y),
        lerp(alpha, p1.z, p2.z),
    )
}

/// `Mth.lerp2(double, double, double x00, double x10, double x01, double x11)`.
pub fn lerp2(alpha1: f64, alpha2: f64, x00: f64, x10: f64, x01: f64, x11: f64) -> f64 {
    lerp(alpha2, lerp(alpha1, x00, x10), lerp(alpha1, x01, x11))
}

/// `Mth.lerp3(...)`.
#[allow(clippy::too_many_arguments)]
pub fn lerp3(
    alpha1: f64,
    alpha2: f64,
    alpha3: f64,
    x000: f64,
    x100: f64,
    x010: f64,
    x110: f64,
    x001: f64,
    x101: f64,
    x011: f64,
    x111: f64,
) -> f64 {
    lerp(
        alpha3,
        lerp2(alpha1, alpha2, x000, x100, x010, x110),
        lerp2(alpha1, alpha2, x001, x101, x011, x111),
    )
}

/// `Mth.catmullrom(float alpha, float p0, float p1, float p2, float p3)`.
pub fn catmullrom(alpha: f32, p0: f32, p1: f32, p2: f32, p3: f32) -> f32 {
    0.5 * (2.0 * p1
        + (p2 - p0) * alpha
        + (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3) * alpha * alpha
        + (3.0 * p1 - p0 - 3.0 * p2 + p3) * alpha * alpha * alpha)
}

/// `Mth.smoothstep(double x)`.
pub fn smoothstep(x: f64) -> f64 {
    x * x * x * (x * (x * 6.0 - 15.0) + 10.0)
}

/// `Mth.smoothstepDerivative(double x)`.
pub fn smoothstep_derivative(x: f64) -> f64 {
    30.0 * x * x * (x - 1.0) * (x - 1.0)
}

/// `Mth.sign(double number)`.
pub fn sign(number: f64) -> i32 {
    if number == 0.0 {
        0
    } else if number > 0.0 {
        1
    } else {
        -1
    }
}

/// `Mth.rotLerp(float a, float from, float to)`.
pub fn rot_lerp(a: f32, from: f32, to: f32) -> f32 {
    from + a * wrap_degrees_f32(to - from)
}

/// `Mth.rotLerp(double a, double from, double to)`.
pub fn rot_lerp_f64(a: f64, from: f64, to: f64) -> f64 {
    from + a * wrap_degrees_f64(to - from)
}

/// `Mth.rotLerpRad(float a, float from, float to)`.
pub fn rot_lerp_rad(a: f32, from: f32, to: f32) -> f32 {
    let mut diff = to - from;
    while diff < -PI {
        diff += TWO_PI;
    }
    while diff >= PI {
        diff -= TWO_PI;
    }
    from + a * diff
}

/// `Mth.triangleWave(float index, float period)`.
pub fn triangle_wave(index: f32, period: f32) -> f32 {
    ((index % period - period * 0.5).abs() - period * 0.25) / (period * 0.25)
}

/// `Mth.square(float x)`.
pub fn square_f32(x: f32) -> f32 {
    x * x
}

/// `Mth.cube(float x)`.
pub fn cube(x: f32) -> f32 {
    x * x * x
}

/// `Mth.square(double x)`.
pub fn square_f64(x: f64) -> f64 {
    x * x
}

/// `Mth.square(int x)` (wrapping).
pub fn square_i32(x: i32) -> i32 {
    x.wrapping_mul(x)
}

/// `Mth.square(long x)` (wrapping).
pub fn square_i64(x: i64) -> i64 {
    x.wrapping_mul(x)
}

/// `Mth.clampedMap(double value, double fromMin, double fromMax, double toMin, double toMax)`.
pub fn clamped_map(value: f64, from_min: f64, from_max: f64, to_min: f64, to_max: f64) -> f64 {
    clamped_lerp(inverse_lerp(value, from_min, from_max), to_min, to_max)
}

/// `Mth.clampedMap(float ...)`.
pub fn clamped_map_f32(value: f32, from_min: f32, from_max: f32, to_min: f32, to_max: f32) -> f32 {
    clamped_lerp_f32(inverse_lerp_f32(value, from_min, from_max), to_min, to_max)
}

/// `Mth.map(double ...)`.
pub fn map(value: f64, from_min: f64, from_max: f64, to_min: f64, to_max: f64) -> f64 {
    lerp(inverse_lerp(value, from_min, from_max), to_min, to_max)
}

/// `Mth.map(float ...)`.
pub fn map_f32(value: f32, from_min: f32, from_max: f32, to_min: f32, to_max: f32) -> f32 {
    lerp_f32(inverse_lerp_f32(value, from_min, from_max), to_min, to_max)
}

/// `Mth.wobble(double coord)`.
pub fn wobble(coord: f64) -> f64 {
    coord
        + (2.0
            * random_source_create_thread_local_instance_with_seed(floor_d(coord * 3000.0) as i64)
                .next_double()
            - 1.0)
            * 1.0E-7
            / 2.0
}

/// `Mth.roundToward(int input, int multiple)` — the multiply wraps (Java int
/// arithmetic).
pub fn round_toward(input: i32, multiple: i32) -> i32 {
    positive_ceil_div(input, multiple).wrapping_mul(multiple)
}

/// `Mth.roundToward(long input, long multiple)` — the multiply wraps.
pub fn round_toward_i64(input: i64, multiple: i64) -> i64 {
    positive_ceil_div_i64(input, multiple).wrapping_mul(multiple)
}

/// `Mth.positiveCeilDiv(int input, int divisor)` —
/// `-Math.floorDiv(-input, divisor)`. Both unary negations wrap (Java int
/// arithmetic), and `-input` overflows for `Integer.MIN_VALUE`.
pub fn positive_ceil_div(input: i32, divisor: i32) -> i32 {
    floor_div(input.wrapping_neg(), divisor).wrapping_neg()
}

/// `Mth.positiveCeilDiv(long input, long divisor)`.
pub fn positive_ceil_div_i64(input: i64, divisor: i64) -> i64 {
    floor_div_i64(input.wrapping_neg(), divisor).wrapping_neg()
}

/// `Mth.randomBetweenInclusive(RandomSource random, int min, int maxInclusive)` —
/// Java int arithmetic wraps.
pub fn random_between_inclusive<R: RandomSource>(
    random: &mut R,
    min: i32,
    max_inclusive: i32,
) -> i32 {
    random
        .next_int_bound(max_inclusive.wrapping_sub(min).wrapping_add(1))
        .wrapping_add(min)
}

/// `Mth.randomBetween(RandomSource random, float min, float maxExclusive)`.
pub fn random_between<R: RandomSource>(random: &mut R, min: f32, max_exclusive: f32) -> f32 {
    random.next_float() * (max_exclusive - min) + min
}

/// `Mth.normal(RandomSource random, float mean, float deviation)`.
pub fn normal<R: RandomSource>(random: &mut R, mean: f32, deviation: f32) -> f32 {
    mean + random.next_gaussian() as f32 * deviation
}

/// `Mth.lengthSquared(double x, double y)`.
pub fn length_squared(x: f64, y: f64) -> f64 {
    x * x + y * y
}

/// `Mth.length(double x, double y)`.
pub fn length(x: f64, y: f64) -> f64 {
    length_squared(x, y).sqrt()
}

/// `Mth.length(float x, float y)`.
///
/// Java resolves `lengthSquared(double, double)` (both float args widen to
/// double), computes `Math.sqrt` in double, then casts to float — so the Rust
/// port widens to f64 before the sqrt to match `(float)Math.sqrt(...)`
/// bit-for-bit (a pure f32 computation differs by 1 ulp and overflows to inf
/// for |x| beyond ~1.8e19).
pub fn length_f32(x: f32, y: f32) -> f32 {
    let x = x as f64;
    let y = y as f64;
    (x * x + y * y).sqrt() as f32
}

/// `Mth.lengthSquared(double x, double y, double z)`.
pub fn length_squared_xyz(x: f64, y: f64, z: f64) -> f64 {
    x * x + y * y + z * z
}

/// `Mth.length(double x, double y, double z)`.
pub fn length_xyz(x: f64, y: f64, z: f64) -> f64 {
    length_squared_xyz(x, y, z).sqrt()
}

/// `Mth.lengthSquared(float x, float y, float z)`.
pub fn length_squared_xyz_f32(x: f32, y: f32, z: f32) -> f32 {
    x * x + y * y + z * z
}

/// `Mth.quantize(double value, int quantizeResolution)`.
pub fn quantize(value: f64, quantize_resolution: i32) -> i32 {
    floor_d(value / quantize_resolution as f64) * quantize_resolution
}

/// `Mth.outFromOrigin(int origin, int lowerBound, int upperBound)` — the
/// spiral order `0, -1, 1, -2, 2, ...` clamped to `[lower, upper]`. Java
/// returns an `IntStream`; the Rust port returns an iterator.
pub fn out_from_origin(
    origin: i32,
    lower_bound: i32,
    upper_bound: i32,
) -> impl Iterator<Item = i32> {
    out_from_origin_with_step(origin, lower_bound, upper_bound, 1)
}

/// `Mth.outFromOrigin(int origin, int lowerBound, int upperBound, int stepSize)`.
///
/// Faithful to `IntStream.iterate(clampedOrigin, hasNext, next)`: the seed is
/// emitted only if `hasNext(seed)`; each subsequent element is `next(prev)`
/// emitted only if `hasNext(next(prev))` (verified against OpenJDK — the
/// predicate gates each element, including the seed).
pub fn out_from_origin_with_step(
    origin: i32,
    lower_bound: i32,
    upper_bound: i32,
    step_size: i32,
) -> impl Iterator<Item = i32> {
    assert!(
        lower_bound <= upper_bound,
        "upperBound {} expected to be > lowerBound {}",
        upper_bound,
        lower_bound
    );
    assert!(
        step_size >= 1,
        "step size expected to be >= 1, was {}",
        step_size
    );
    let clamped_origin = clamp(origin, lower_bound, upper_bound);
    let mut current = clamped_origin;
    let mut first = true;
    std::iter::from_fn(move || {
        if first {
            first = false;
            if has_out_of_origin_next(clamped_origin, lower_bound, upper_bound, current) {
                Some(current)
            } else {
                None
            }
        } else {
            let next =
                out_of_origin_next(clamped_origin, lower_bound, upper_bound, step_size, current);
            if has_out_of_origin_next(clamped_origin, lower_bound, upper_bound, next) {
                current = next;
                Some(next)
            } else {
                None
            }
        }
    })
}

/// `IntStream.iterate`'s `hasNext` predicate:
/// `clampedOrigin - currentDistance >= lowerBound || clampedOrigin + currentDistance <= upperBound`.
fn has_out_of_origin_next(
    clamped_origin: i32,
    lower_bound: i32,
    upper_bound: i32,
    cursor: i32,
) -> bool {
    let current_distance = clamped_origin.wrapping_sub(cursor).wrapping_abs();
    clamped_origin.wrapping_sub(current_distance) >= lower_bound
        || clamped_origin.wrapping_add(current_distance) <= upper_bound
}

/// The `IntStream.iterate` `next` function.
fn out_of_origin_next(
    clamped_origin: i32,
    lower_bound: i32,
    upper_bound: i32,
    step_size: i32,
    cursor: i32,
) -> i32 {
    let previous_was_negative = cursor <= clamped_origin;
    let current_distance = clamped_origin.wrapping_sub(cursor).wrapping_abs();
    let can_move_positive = clamped_origin
        .wrapping_add(current_distance)
        .wrapping_add(step_size)
        <= upper_bound;
    if !previous_was_negative || !can_move_positive {
        let attempted_step = clamped_origin
            .wrapping_sub(current_distance)
            .wrapping_sub(if previous_was_negative { step_size } else { 0 });
        if attempted_step >= lower_bound {
            return attempted_step;
        }
    }
    clamped_origin
        .wrapping_add(current_distance)
        .wrapping_add(step_size)
}

/// `Mth.rotationAroundAxis(Vector3fc axis, Quaternionf rotation, Quaternionf result)`.
///
/// JOML's `Vector3f.dot(float,float,float)` and `Quaternionf.normalize()` use
/// fused `Math.fma` (verified against joml-1.10.8 bytecode), so the port uses
/// `f32::mul_add` to stay bit-exact.
pub fn rotation_around_axis(axis: Vec3f, rotation: Quaternionf) -> Quaternionf {
    let projected_length = axis.dot(rotation.x, rotation.y, rotation.z);
    Quaternionf {
        x: axis.x * projected_length,
        y: axis.y * projected_length,
        z: axis.z * projected_length,
        w: rotation.w,
    }
    .normalized()
}

/// `Mth.rayIntersectsAABB(Vec3 rayStart, Vec3 rayDir, AABB aabb)` — the
/// slab/Andrew-Woo test.
pub fn ray_intersects_aabb(ray_start: Vec3, ray_dir: Vec3, aabb: Aabb) -> bool {
    let center_x = (aabb.min_x + aabb.max_x) * 0.5;
    let box_extent_x = (aabb.max_x - aabb.min_x) * 0.5;
    let diff_x = ray_start.x - center_x;
    if diff_x.abs() > box_extent_x && diff_x * ray_dir.x >= 0.0 {
        return false;
    }
    let center_y = (aabb.min_y + aabb.max_y) * 0.5;
    let box_extent_y = (aabb.max_y - aabb.min_y) * 0.5;
    let diff_y = ray_start.y - center_y;
    if diff_y.abs() > box_extent_y && diff_y * ray_dir.y >= 0.0 {
        return false;
    }
    let center_z = (aabb.min_z + aabb.max_z) * 0.5;
    let box_extent_z = (aabb.max_z - aabb.min_z) * 0.5;
    let diff_z = ray_start.z - center_z;
    if diff_z.abs() > box_extent_z && diff_z * ray_dir.z >= 0.0 {
        return false;
    }
    let andrew_woo_diff_x = ray_dir.x.abs();
    let andrew_woo_diff_y = ray_dir.y.abs();
    let andrew_woo_diff_z = ray_dir.z.abs();
    let mut f = ray_dir.y * diff_z - ray_dir.z * diff_y;
    if f.abs() > box_extent_y * andrew_woo_diff_z + box_extent_z * andrew_woo_diff_y {
        return false;
    }
    f = ray_dir.z * diff_x - ray_dir.x * diff_z;
    if f.abs() > box_extent_x * andrew_woo_diff_z + box_extent_z * andrew_woo_diff_x {
        return false;
    }
    f = ray_dir.x * diff_y - ray_dir.y * diff_x;
    f.abs() < box_extent_x * andrew_woo_diff_y + box_extent_y * andrew_woo_diff_x
}

/// `Mth.mulAndTruncate(Fraction fraction, int factor)` — Apache Commons
/// `Fraction.getNumerator() * factor / getDenominator()` (int, wrapping).
pub fn mul_and_truncate(fraction: &Fraction, factor: i32) -> i32 {
    fraction.numerator.wrapping_mul(factor) / fraction.denominator
}

#[cfg(test)]
#[path = "mth_golden_tests.rs"]
mod mth_golden_tests;

#[cfg(test)]
mod tests {
    // Hand-written unit tests for `Mth.absMax` float/double boundary behavior
    // (signed zero, NaN). These are not in the generated golden oracle, which only
    // covers the `absMax(int, int)` overload. Expected values are grounded in the
    // pinned JDK 25 (`working/Paper` toolchain) live probes of
    // `Math.max(Math.abs(a), Math.abs(b))`.
    use super::{abs_max_f32, abs_max_f64};

    #[test]
    fn abs_max_f64_signed_zero_matches_java_math_max() {
        // `Math.abs(±0.0)` is `+0.0`, so `Math.max(Math.abs(a), Math.abs(b))` is
        // positive zero in every ordering.
        assert!(abs_max_f64(0.0, 0.0).is_sign_positive());
        assert!(abs_max_f64(-0.0, 0.0).is_sign_positive());
        assert!(abs_max_f64(0.0, -0.0).is_sign_positive());
        assert!(abs_max_f64(-0.0, -0.0).is_sign_positive());
        assert_eq!(abs_max_f64(-0.0, 0.0).to_bits(), 0.0f64.to_bits());
    }

    #[test]
    fn abs_max_f64_propagates_nan_from_either_operand() {
        // Java `Math.max` returns NaN if either argument is NaN; Rust `f64::max`
        // would return the non-NaN operand instead (the original defect).
        assert!(abs_max_f64(f64::NAN, 5.0).is_nan());
        assert!(abs_max_f64(5.0, f64::NAN).is_nan());
        assert!(abs_max_f64(f64::NAN, f64::NAN).is_nan());
        // Absing first matches Java: `Math.abs` clears a NaN's sign bit while preserving
        // its payload. These inputs are canonical NaNs (zero payload), so the propagated
        // NaN is canonical even for an explicitly negative NaN.
        assert_eq!(abs_max_f64(f64::NAN, 5.0).to_bits(), f64::NAN.to_bits());
        assert_eq!(
            abs_max_f64(f64::from_bits(0xfff8_0000_0000_0000), 5.0).to_bits(),
            f64::NAN.to_bits()
        );
        // NaN wins over any magnitude, including infinities and signed zero.
        assert!(abs_max_f64(f64::NAN, f64::NEG_INFINITY).is_nan());
        assert!(abs_max_f64(f64::INFINITY, f64::NAN).is_nan());
        assert!(abs_max_f64(f64::NAN, -0.0).is_nan());
    }

    #[test]
    fn abs_max_f32_signed_zero_matches_java_math_max() {
        assert!(abs_max_f32(0.0f32, 0.0).is_sign_positive());
        assert!(abs_max_f32(-0.0f32, 0.0).is_sign_positive());
        assert!(abs_max_f32(0.0f32, -0.0).is_sign_positive());
        assert!(abs_max_f32(-0.0f32, -0.0).is_sign_positive());
        assert_eq!(abs_max_f32(-0.0f32, 0.0).to_bits(), 0.0f32.to_bits());
    }

    #[test]
    fn abs_max_f32_propagates_nan_from_either_operand() {
        assert!(abs_max_f32(f32::NAN, 5.0f32).is_nan());
        assert!(abs_max_f32(5.0f32, f32::NAN).is_nan());
        assert!(abs_max_f32(f32::NAN, f32::NAN).is_nan());
        // Same canonicalization as the f64 case above.
        assert_eq!(abs_max_f32(f32::NAN, 5.0f32).to_bits(), f32::NAN.to_bits());
        assert_eq!(
            abs_max_f32(f32::from_bits(0xffc0_0000), 5.0f32).to_bits(),
            f32::NAN.to_bits()
        );
        assert!(abs_max_f32(f32::NAN, f32::NEG_INFINITY).is_nan());
        assert!(abs_max_f32(f32::INFINITY, f32::NAN).is_nan());
        assert!(abs_max_f32(f32::NAN, -0.0f32).is_nan());
    }
}
