//! `net.minecraft.world.level.levelgen.synth` — the worldgen primitive-noise
//! value classes (issue #177).
//!
//! Ports the seven pure-vanilla `synth` classes: `SimplexNoise`,
//! `ImprovedNoise`, `PerlinSimplexNoise`, `PerlinNoise`, `NormalNoise`,
//! `BlendedNoise`, and `NoiseUtils`. These are value leaves over the exact
//! RNG/permutation/interpolation machinery in `rivet-util` (`random`,
//! `worldgen_random`, `mth`); exact-bit golden tests pin every class against
//! the committed Paper-oracle fixture
//! (`tools/rivet-oracle/fixtures/synth/synth-noise.json`, generated by
//! `tools/rivet-oracle/src/java/SynthNoiseProbe.java`).
//!
//! Deferred seams (kept minimal, issue-linked):
//! - `DensityFunction` / the noise-router layer is NOT ported here (issue
//!   #177 waves the full `noise` unit): `BlendedNoise` exposes its value
//!   surface (`compute`/`min_value`/`max_value`) directly instead of
//!   implementing `DensityFunction.SimpleFunction`, and the DFU codecs
//!   (`BlendedNoise.CODEC`, `NormalNoise.NoiseParameters.CODEC`) stay stubs —
//!   RivetTodo(#177).
//!
//! All probabilities/permutation sizes here mirror the Java 1:1; see each
//! module doc for the Java class it ports.

pub mod blended_noise;
pub mod improved_noise;
pub mod noise_utils;
pub mod normal_noise;
pub mod perlin_noise;
pub mod perlin_simplex_noise;
pub mod simplex_noise;
