// Generated by `tools/rivet-codegen generate` from data/biomes_tags.json
// (live Paper registry load via BiomeTagExtractor; MC 26.2, protocol 776, world 4903).
// Source jar sha256 e1a027e9481a16ec; provenance linked to data/biomes_tags.manifest.json.
// Do not edit by hand — PORTING.md: registries/data are generated, not hand-ported.

// `minecraft:worldgen/biome` id/name table, dense 0..n (element id == holder id
// == network id == insertion index; OWNERSHIP.md §Registries). Biome ids are
// assigned at runtime from a `TreeMap<Identifier, Resource>` sorted by
// `Identifier` compareTo (path first, then namespace) — id 0 is
// `minecraft:badlands`, alphabetical. The global palette of
// `PalettedContainer<Holder<Biome>>` (chunk.access) indexes this table.

/// `minecraft:worldgen/biome` — biome name -> registry id (dense `0..66`).
pub static BIOME_BY_NAME: phf::Map<&'static str, u16> = phf::phf_map! {
    "minecraft:badlands" => 0u16,
    "minecraft:bamboo_jungle" => 1u16,
    "minecraft:basalt_deltas" => 2u16,
    "minecraft:beach" => 3u16,
    "minecraft:birch_forest" => 4u16,
    "minecraft:cherry_grove" => 5u16,
    "minecraft:cold_ocean" => 6u16,
    "minecraft:crimson_forest" => 7u16,
    "minecraft:dark_forest" => 8u16,
    "minecraft:deep_cold_ocean" => 9u16,
    "minecraft:deep_dark" => 10u16,
    "minecraft:deep_frozen_ocean" => 11u16,
    "minecraft:deep_lukewarm_ocean" => 12u16,
    "minecraft:deep_ocean" => 13u16,
    "minecraft:desert" => 14u16,
    "minecraft:dripstone_caves" => 15u16,
    "minecraft:end_barrens" => 16u16,
    "minecraft:end_highlands" => 17u16,
    "minecraft:end_midlands" => 18u16,
    "minecraft:eroded_badlands" => 19u16,
    "minecraft:flower_forest" => 20u16,
    "minecraft:forest" => 21u16,
    "minecraft:frozen_ocean" => 22u16,
    "minecraft:frozen_peaks" => 23u16,
    "minecraft:frozen_river" => 24u16,
    "minecraft:grove" => 25u16,
    "minecraft:ice_spikes" => 26u16,
    "minecraft:jagged_peaks" => 27u16,
    "minecraft:jungle" => 28u16,
    "minecraft:lukewarm_ocean" => 29u16,
    "minecraft:lush_caves" => 30u16,
    "minecraft:mangrove_swamp" => 31u16,
    "minecraft:meadow" => 32u16,
    "minecraft:mushroom_fields" => 33u16,
    "minecraft:nether_wastes" => 34u16,
    "minecraft:ocean" => 35u16,
    "minecraft:old_growth_birch_forest" => 36u16,
    "minecraft:old_growth_pine_taiga" => 37u16,
    "minecraft:old_growth_spruce_taiga" => 38u16,
    "minecraft:pale_garden" => 39u16,
    "minecraft:plains" => 40u16,
    "minecraft:river" => 41u16,
    "minecraft:savanna" => 42u16,
    "minecraft:savanna_plateau" => 43u16,
    "minecraft:small_end_islands" => 44u16,
    "minecraft:snowy_beach" => 45u16,
    "minecraft:snowy_plains" => 46u16,
    "minecraft:snowy_slopes" => 47u16,
    "minecraft:snowy_taiga" => 48u16,
    "minecraft:soul_sand_valley" => 49u16,
    "minecraft:sparse_jungle" => 50u16,
    "minecraft:stony_peaks" => 51u16,
    "minecraft:stony_shore" => 52u16,
    "minecraft:sulfur_caves" => 53u16,
    "minecraft:sunflower_plains" => 54u16,
    "minecraft:swamp" => 55u16,
    "minecraft:taiga" => 56u16,
    "minecraft:the_end" => 57u16,
    "minecraft:the_void" => 58u16,
    "minecraft:warm_ocean" => 59u16,
    "minecraft:warped_forest" => 60u16,
    "minecraft:windswept_forest" => 61u16,
    "minecraft:windswept_gravelly_hills" => 62u16,
    "minecraft:windswept_hills" => 63u16,
    "minecraft:windswept_savanna" => 64u16,
    "minecraft:wooded_badlands" => 65u16,
};

/// `minecraft:worldgen/biome` — biome names indexed by registry id (id == index).
pub static BIOME_BY_ID: &[&str] = &[
    "minecraft:badlands", // 0
    "minecraft:bamboo_jungle", // 1
    "minecraft:basalt_deltas", // 2
    "minecraft:beach", // 3
    "minecraft:birch_forest", // 4
    "minecraft:cherry_grove", // 5
    "minecraft:cold_ocean", // 6
    "minecraft:crimson_forest", // 7
    "minecraft:dark_forest", // 8
    "minecraft:deep_cold_ocean", // 9
    "minecraft:deep_dark", // 10
    "minecraft:deep_frozen_ocean", // 11
    "minecraft:deep_lukewarm_ocean", // 12
    "minecraft:deep_ocean", // 13
    "minecraft:desert", // 14
    "minecraft:dripstone_caves", // 15
    "minecraft:end_barrens", // 16
    "minecraft:end_highlands", // 17
    "minecraft:end_midlands", // 18
    "minecraft:eroded_badlands", // 19
    "minecraft:flower_forest", // 20
    "minecraft:forest", // 21
    "minecraft:frozen_ocean", // 22
    "minecraft:frozen_peaks", // 23
    "minecraft:frozen_river", // 24
    "minecraft:grove", // 25
    "minecraft:ice_spikes", // 26
    "minecraft:jagged_peaks", // 27
    "minecraft:jungle", // 28
    "minecraft:lukewarm_ocean", // 29
    "minecraft:lush_caves", // 30
    "minecraft:mangrove_swamp", // 31
    "minecraft:meadow", // 32
    "minecraft:mushroom_fields", // 33
    "minecraft:nether_wastes", // 34
    "minecraft:ocean", // 35
    "minecraft:old_growth_birch_forest", // 36
    "minecraft:old_growth_pine_taiga", // 37
    "minecraft:old_growth_spruce_taiga", // 38
    "minecraft:pale_garden", // 39
    "minecraft:plains", // 40
    "minecraft:river", // 41
    "minecraft:savanna", // 42
    "minecraft:savanna_plateau", // 43
    "minecraft:small_end_islands", // 44
    "minecraft:snowy_beach", // 45
    "minecraft:snowy_plains", // 46
    "minecraft:snowy_slopes", // 47
    "minecraft:snowy_taiga", // 48
    "minecraft:soul_sand_valley", // 49
    "minecraft:sparse_jungle", // 50
    "minecraft:stony_peaks", // 51
    "minecraft:stony_shore", // 52
    "minecraft:sulfur_caves", // 53
    "minecraft:sunflower_plains", // 54
    "minecraft:swamp", // 55
    "minecraft:taiga", // 56
    "minecraft:the_end", // 57
    "minecraft:the_void", // 58
    "minecraft:warm_ocean", // 59
    "minecraft:warped_forest", // 60
    "minecraft:windswept_forest", // 61
    "minecraft:windswept_gravelly_hills", // 62
    "minecraft:windswept_hills", // 63
    "minecraft:windswept_savanna", // 64
    "minecraft:wooded_badlands", // 65
];

/// Number of vanilla biomes (the biome registry size).
pub const BIOME_COUNT: usize = 66;
