//! The deterministic seed/coordinate corpus for the #54 chunk-hash engine.
//!
//! The corpus is the single source of truth read by both the Paper manifest
//! generator and the comparator: which world seeds, and which chunk
//! coordinates, a green Paper-vs-Rivet sweep must cover. It is committed as
//! `fixtures/chunk-hash/corpus.json` (a test asserts the on-disk file equals
//! the derivation here), so a future seed/generator change is a deliberate,
//! reviewed edit — never a silent one in generator code.
//!
//! Recipe (documented in the committed `corpus.json` `recipe` field):
//!   `seed[i] = u64::from_be_bytes(sha256("rivet-m2-seed-corpus-v1")[i*8..][..8])`
//! The coordinates are the #175 §2 matrix spelled out explicitly — positive
//! (0,0)/(15,15)/(31,31), negative (-1,-1)/(-16,-16)/(-31,-31), region seams
//! (-1,0)/(0,-1), and the corner/center (0,0) — including negative coordinates
//! so cross-region serialization (a chunk whose columns straddle an x/z=31
//! seam) is covered. Only (0,0) exists in the committed M2 region capture; the
//! rest are the *target* that live FULL generation must reach. Coverage is
//! always reported, never assumed.

use sha2::Digest;

/// The recipe string whose SHA-256 derives the corpus seeds.
pub const RECIPE: &str = "rivet-m2-seed-corpus-v1";

/// How many seeds the corpus defines.
pub const SEED_COUNT: usize = 4;

/// The chunk coordinates a green sweep must cover (a flat list of (x, z)
/// pairs; `dim` is added by the manifest generator, which sweeps every
/// dimension's region file).
pub const COORDINATES: &[(i32, i32)] = &[
    (0, 0),
    (15, 15),
    (31, 31),
    (-1, -1),
    (-16, -16),
    (-31, -31),
    (-1, 0),
    (0, -1),
];

/// The parsed corpus: the seeds a green sweep must be generated under, and the
/// chunk coordinates it must cover. Both come from the committed `corpus.json`
/// (the single source of truth); this struct is the in-memory form.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Corpus {
    pub seeds: Vec<u64>,
    pub coordinates: Vec<(i32, i32)>,
}

impl Corpus {
    /// The corpus as committed (derived here, asserted equal to the file by a
    /// test — the code and the committed file can never drift).
    pub fn from_committed() -> Corpus {
        Corpus {
            seeds: corpus_seeds(),
            coordinates: COORDINATES.to_vec(),
        }
    }
}

/// Derive the i-th corpus seed per the recipe. `i` is clamped so an out-of-range
/// index still produces a deterministic value (the committed file pins exactly
/// `SEED_COUNT` seeds; a larger `i` is a code bug caught by the equality test).
pub fn corpus_seed(i: usize) -> u64 {
    let digest = sha2::Sha256::digest(RECIPE.as_bytes());
    let bytes = digest.as_slice();
    let base = (i * 8).min(bytes.len().saturating_sub(8));
    let mut out = [0u8; 8];
    out.copy_from_slice(&bytes[base..base + 8]);
    u64::from_be_bytes(out)
}

/// All corpus seeds, in order.
pub fn corpus_seeds() -> Vec<u64> {
    (0..SEED_COUNT).map(corpus_seed).collect()
}

/// Serialize the corpus exactly as the committed `corpus.json` (sorted keys,
/// `serde_json` pretty with a trailing newline) so the committed file can be
/// regenerated byte-identically and compared. Test-only: the committed file is
/// the single source of truth, and the only consumer is the equality test.
#[cfg(test)]
pub fn corpus_json() -> serde_json::Value {
    serde_json::json!({
        "recipe": format!("sha256(\"{RECIPE}\") -> u64::from_be_bytes(block)"),
        "hash-algorithm": "xxh3_64",
        "seed-count": SEED_COUNT,
        "seeds": corpus_seeds(),
        "coordinates": COORDINATES
            .iter()
            .map(|(x, z)| json_coord(*x, *z))
            .collect::<Vec<_>>(),
    })
}

#[cfg(test)]
fn json_coord(x: i32, z: i32) -> serde_json::Value {
    serde_json::json!({ "x": x, "z": z })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixtures_corpus() -> Option<serde_json::Value> {
        let path = crate_dir().join("fixtures/chunk-hash/corpus.json");
        let text = std::fs::read_to_string(&path).ok()?;
        serde_json::from_str(&text).ok()
    }

    fn crate_dir() -> std::path::PathBuf {
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
    }

    /// The committed corpus must equal the derivation here (single source of
    /// truth — the committed file never drifts from the code).
    #[test]
    fn corpus_matches_committed() {
        let committed = fixtures_corpus().expect("fixtures/chunk-hash/corpus.json committed");
        assert_eq!(committed, corpus_json());
    }

    #[test]
    fn seeds_are_stable() {
        // Pinned anchor values derived at wiring time; guards the recipe
        // against an accidental change (a changed recipe would silently retarget
        // every digest in the committed manifests).
        let seeds = corpus_seeds();
        assert_eq!(
            seeds,
            vec![
                5207638315753790570,
                12807505919197044144,
                5246862266665176429,
                3423572188437197996,
            ]
        );
    }

    #[test]
    fn coordinates_cover_negative_and_seams() {
        let xs: Vec<i32> = COORDINATES.iter().map(|(x, _)| *x).collect();
        let zs: Vec<i32> = COORDINATES.iter().map(|(_, z)| *z).collect();
        assert!(xs.iter().any(|&x| x < 0) && zs.iter().any(|&z| z < 0));
        assert!(COORDINATES.contains(&(-1, 0)) && COORDINATES.contains(&(0, -1)));
        assert_eq!(COORDINATES.len(), 8);
    }
}
