#!/usr/bin/env python3
"""Regenerate `crates/rivet-nbt/src/unicode_name_table_generated.rs` from the
committed Unicode character-name / block / assigned tables.

Sources (all committed under `tools/rivet-codegen/data/`):

* `unicode_names.tsv` — the canonical `Character.codePointOf` name database,
  decoded once from the OpenJDK `java.base` `java/lang/uniName.dat` (Temurin
  25.0.2, Unicode 16.0). Rows are `NAME<TAB>CODE_POINT_HEX`.
* `unicode_blocks.tsv` — `UnicodeBlock` boundaries: maximal runs of constant
  `Character.UnicodeBlock.of(cp).toString().replace('_',' ')`, extracted from
  the same JDK. Rows are `START_CODE_POINT_HEX<TAB>BLOCK_NAME`; the sentinel
  name `<none>` marks ranges where `UnicodeBlock.of` is null.
* `unicode_assigned.tsv` — maximal runs of `Character.getType(cp) != UNASSIGNED`
  (code points with an assigned category), same JDK. Rows are
  `START_HEX<TAB>END_HEX`.

Together they reproduce `Character.codePointOf`'s hex fallback: the algorithm
names code points not present in the name table as
`UnicodeBlock.of(cp).toString().replace('_',' ') + " " + toHexString(cp)`.

Deterministic and idempotent: running this over the current committed output
reproduces it byte-for-byte (`git diff` stays clean).
"""

from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC_NAMES = REPO / "tools/rivet-codegen/data/unicode_names.tsv"
SRC_BLOCKS = REPO / "tools/rivet-codegen/data/unicode_blocks.tsv"
SRC_ASSIGNED = REPO / "tools/rivet-codegen/data/unicode_assigned.tsv"
OUT = REPO / "crates/rivet-nbt/src/unicode_name_table_generated.rs"

MAX_CP = 0x10FFFF

HEADER = """\
// Generated by `scripts/gen_unicode_names.py` from
// tools/rivet-codegen/data/{names,blocks,assigned}.tsv (decoded from the
// OpenJDK java.base `java/lang/uniName.dat` and the `Character` / `UnicodeBlock`
// property tables — the `Character.codePointOf` algorithm). Do not edit by
// hand — regenerate with:
//   python3 scripts/gen_unicode_names.py
//
// `NAME_TO_CODEPOINT` is the canonical-name table (Java `CharacterName`).
// `CODEPOINT_TO_NAME` inverts it for the fallback's exact-match check
// (`Character.getName`). `BLOCK_STARTS` / `BLOCK_NAMES` and `ASSIGNED_RANGES`
// reproduce the algorithmic name `UnicodeBlock.of(cp).toString().replace('_',
// ' ') + " " + Integer.toHexString(cp)`, gated by `getType != UNASSIGNED`.
"""


def load_names() -> list[tuple[str, int]]:
    entries = []
    for line in SRC_NAMES.read_text().splitlines():
        if not line:
            continue
        name, cp_hex = line.split("\t", 1)
        assert name.isascii(), f"non-ASCII name {name!r}"
        assert all(
            c.isupper() or c in "- ()" or c.isdigit() for c in name
        ), f"unexpected name {name!r}"
        entries.append((name, int(cp_hex, 16)))
    assert len(entries) == len({n for n, _ in entries}), "duplicate names in source"
    return entries


def load_blocks() -> list[tuple[int, str]]:
    blocks = []
    for line in SRC_BLOCKS.read_text().splitlines():
        if not line:
            continue
        start_hex, name = line.split("\t", 1)
        blocks.append((int(start_hex, 16), name))
    assert blocks[0][0] == 0, "first block must start at 0"
    assert blocks[-1][0] <= MAX_CP, "last block must start at or before MAX_CP"
    for i in range(1, len(blocks)):
        assert blocks[i][0] > blocks[i - 1][0], "blocks must be strictly sorted"
    return blocks


def load_assigned() -> list[tuple[int, int]]:
    ranges = []
    for line in SRC_ASSIGNED.read_text().splitlines():
        if not line:
            continue
        s_hex, e_hex = line.split("\t", 1)
        s, e = int(s_hex, 16), int(e_hex, 16)
        assert 0 <= s <= e <= MAX_CP, f"bad assigned range {line!r}"
        ranges.append((s, e))
    assert ranges[0][0] == 0, "first assigned range must start at 0"
    for i in range(1, len(ranges)):
        assert ranges[i][0] > ranges[i - 1][1], "assigned ranges must be disjoint+ordered"
    return ranges


def main() -> None:
    names = load_names()
    blocks = load_blocks()
    assigned = load_assigned()
    rev = {}
    for n, cp in names:
        assert cp not in rev, f"duplicate code point {cp:#x}"
        rev[cp] = n

    body = ",\n".join(f'    "{n}" => {cp:#08x}u32' for n, cp in names)
    rev_body = ",\n".join(f"    {cp:#08x}u32 => \"{n}\"" for cp, n in sorted(rev.items()))
    block_starts = ",\n".join(f"    {s:#08x}u32" for s, _ in blocks)
    def rust_str(s: str) -> str:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    block_names = ",\n".join(
        f"    {'Some(' + rust_str(n) + ')' if n != '<none>' else 'None'}"
        for _, n in blocks
    )
    assigned_body = ",\n".join(f"    ({s:#08x}u32, {e:#08x}u32)" for s, e in assigned)

    out = f"{HEADER}\n"
    out += "/// Canonical Unicode character name -> code point (Java `CharacterName`).\n"
    out += "pub static NAME_TO_CODEPOINT: phf::Map<&'static str, u32> = phf::phf_map! {\n"
    out += body
    out += ",\n};\n\n"
    out += "/// Code point -> canonical name (Java `Character.getName`, table half).\n"
    out += "pub static CODEPOINT_TO_NAME: phf::Map<u32, &'static str> = phf::phf_map! {\n"
    out += rev_body
    out += ",\n};\n\n"
    out += "/// `UnicodeBlock.of(cp).toString().replace('_',' ')` block start code\n"
    out += "/// points, sorted (Java). The matching entry in `BLOCK_NAMES` may be\n"
    out += "/// `None` for ranges where `UnicodeBlock.of` returns null.\n"
    out += "pub static BLOCK_STARTS: &[u32] = &[\n"
    out += block_starts
    out += ",\n];\n\n"
    out += "/// Block names for each `BLOCK_STARTS` entry; `None` for `<none>`.\n"
    out += "pub static BLOCK_NAMES: &[Option<&'static str>] = &[\n"
    out += block_names
    out += "\n];\n\n"
    out += "/// `Character.getType(cp) != UNASSIGNED` maximal inclusive ranges (Java).\n"
    out += "pub static ASSIGNED_RANGES: &[(u32, u32)] = &[\n"
    out += assigned_body
    out += ",\n];\n\n"

    # Self-tests derived purely from the committed data. `code_point_of` lives
    # in `unicode_name_table.rs` (which `include!`s this file).
    out += "#[cfg(test)]\n"
    out += "mod self_tests {\n"
    out += "    use super::*;\n"
    out += "    use crate::unicode_name_table::{code_point_of, CodePointOfError};\n\n"
    out += "    #[test]\n"
    out += "    fn every_table_name_resolves_to_its_code_point() {\n"
    out += "        for (name, cp) in NAME_TO_CODEPOINT.entries() {\n"
    out += "            assert_eq!(code_point_of(name), Ok(*cp), \"name {name}\");\n"
    out += "        }\n"
    out += "    }\n\n"
    out += "    #[test]\n"
    out += "    fn reverse_map_is_exact() {\n"
    out += "        for (name, cp) in NAME_TO_CODEPOINT.entries() {\n"
    out += "            assert_eq!(CODEPOINT_TO_NAME.get(cp), Some(name), \"cp {cp:#x}\");\n"
    out += "        }\n"
    out += "    }\n\n"
    out += "    #[test]\n"
    out += "    fn algorithmic_fallback_per_block() {\n"
    out += "        // For every named block, the first assigned & unnamed code point\n"
    out += "        // resolves via its block+hex name, and the zero-padded spelling\n"
    out += "        // (Java `getName` never pads) does not.\n"
    for (s, bname), (s2, _) in zip(blocks, blocks[1:] + [(MAX_CP + 1, "")]):
        if bname == "<none>":
            continue
        end = s2 - 1
        # first assigned cp in [s, end] not in rev
        cp = None
        for a_s, a_e in assigned:
            lo = max(s, a_s)
            hi = min(end, a_e)
            if lo <= hi:
                for c in range(lo, hi + 1):
                    if c not in rev:
                        cp = c
                        break
            if cp is not None:
                break
        if cp is None:
            continue
        plain = f"{bname} {cp:X}"
        if 0xD800 <= cp <= 0xDFFF:
            # Lone surrogate: Rust reports the documented divergence, not a
            # valid code point.
            out += f"        assert_eq!(code_point_of(\"{plain}\"), Err(CodePointOfError::LoneSurrogate({cp:#x}u32)));\n"
        else:
            out += f"        assert_eq!(code_point_of(\"{plain}\"), Ok({cp:#x}u32));\n"
        padded = f"{bname} {cp:04X}"
        if padded != plain:
            out += f"        assert!(matches!(code_point_of(\"{padded}\"), Err(CodePointOfError::UnknownName)));\n"
    out += "    }\n"
    out += "}\n"

    OUT.write_text(out)
    print(
        f"wrote {len(names)} names, {len(blocks)} blocks, "
        f"{len(assigned)} assigned ranges to {OUT.relative_to(REPO)}"
    )


if __name__ == "__main__":
    main()
