//! Golden spot-checks of the generated packet-ID tables (feature `packets`).
//!
//! The tables are generated by `tools/rivet-codegen generate` from the pinned
//! `data/reports/packets.json` (vanilla `PacketReport`); the no-drift gate for
//! the generated source lives in the codegen crate. These tests assert the
//! public API works and pins a few addPacket-order facts that #84 (packet
//! registration) depends on — e.g. the play/clientbound boundary packet is
//! `bundle_delimiter` at id 0.
//!
//! Gated behind the `packets` feature via `required-features` in Cargo.toml.

use rivet_protocol::generated::packets::play;
use rivet_protocol::generated::packets::play::clientbound::{self, PacketType as PlayClientbound};
use rivet_protocol::generated::packets::play::serverbound::PacketType as PlayServerbound;
use rivet_protocol::generated::protocol::{ConnectionProtocol, PacketFlow};

#[test]
fn play_clientbound_add_packet_order() {
    // `withBundlePacket` registers the delimiter first, so it owns id 0; the
    // first body packet (add_entity) is id 1.
    assert_eq!(PlayClientbound::BundleDelimiter.id(), 0);
    assert_eq!(PlayClientbound::AddEntity.id(), 1);
    assert_eq!(clientbound::ALL[0], PlayClientbound::BundleDelimiter);
    assert_eq!(clientbound::ALL[1], PlayClientbound::AddEntity);
    assert_eq!(PlayClientbound::ShowDialog.id(), 140);
}

#[test]
fn play_serverbound_add_packet_order() {
    assert_eq!(PlayServerbound::AcceptTeleportation.id(), 0);
    assert_eq!(PlayServerbound::Attack.id(), 1);
    assert_eq!(PlayServerbound::CustomClickAction.id(), 68);
}

#[test]
fn id_and_name_are_inverse() {
    let sb = play::serverbound::PacketType::AcceptTeleportation;
    assert_eq!(PlayServerbound::from_id(sb.id()), Some(sb));
    assert_eq!(PlayServerbound::from_name(sb.name()), Some(sb));
    assert_eq!(PlayServerbound::from_id(999), None);
    assert_eq!(PlayServerbound::from_name("minecraft:does_not_exist"), None);
}

#[test]
fn protocol_and_flow_enums() {
    assert_eq!(ConnectionProtocol::Handshake.id(), "handshake");
    assert_eq!(
        ConnectionProtocol::from_id("play"),
        Some(ConnectionProtocol::Play)
    );
    assert_eq!(ConnectionProtocol::from_id("bogus"), None);
    assert_eq!(
        ConnectionProtocol::ALL,
        [
            ConnectionProtocol::Handshake,
            ConnectionProtocol::Play,
            ConnectionProtocol::Status,
            ConnectionProtocol::Login,
            ConnectionProtocol::Configuration,
        ]
    );

    assert_eq!(PacketFlow::Serverbound.id(), "serverbound");
    assert_eq!(PacketFlow::Clientbound.id(), "clientbound");
    assert_eq!(PacketFlow::Serverbound.opposite(), PacketFlow::Clientbound);
    assert_eq!(PacketFlow::Clientbound.opposite(), PacketFlow::Serverbound);
    assert_eq!(
        PacketFlow::from_id("clientbound"),
        Some(PacketFlow::Clientbound)
    );
}

#[test]
fn names_are_canonical_packet_names() {
    assert_eq!(
        PlayClientbound::BundleDelimiter.name(),
        "minecraft:bundle_delimiter"
    );
    assert_eq!(PlayClientbound::AddEntity.name(), "minecraft:add_entity");
}
